{{- if and .Values.security.enabled (not .Values.initialConfiguration.settings.existingConfigmap) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "graphdb.fullname.configmap.settings" . }}
  namespace: {{ include "graphdb.namespace" . }}
  labels:
    {{- include "graphdb.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
data:
  {{ .Values.initialConfiguration.settings.configmapKey }}: |-
    {{- tpl (.Files.Get "files/config/settings.js" | trim) . | nindent 4 }}
{{- end }}
