apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "graphdb.fullname.configmap.environment" . }}
  namespace: {{ include "graphdb.namespace" . }}
  labels:
    {{- include "graphdb.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
data:
  GDB_JAVA_OPTS: >-
    -Dgraphdb.home=/opt/graphdb/home
    -Dhttp.socket.keepalive=true
    {{ .Values.configuration.defaultJavaArguments }}
    {{ .Values.configuration.javaArguments }}
