{{- if not .Values.configuration.properties.existingConfigmap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "graphdb.fullname.configmap.properties" . }}
  labels:
    {{- include "graphdb.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- tpl ( toYaml . ) $ | nindent 4 }}
  {{- end }}
data:
  {{ .Values.configuration.properties.configmapKey }}: |-
    {{- tpl ( .Files.Get "files/config/graphdb.properties" | trim ) . | nindent 4 }}
    {{- if .Values.properties }}
    ##### Overrides from values.yaml #####
    {{ range $key, $val := .Values.properties }}
    {{- if ne $val nil }}
    {{- $key }}={{ tpl ($val | toString) $ | quote }}
    {{- end }}
    {{- end }}
    {{- end }}
{{- end }}
