{{- if not .Values.configuration.properties.existingConfigmap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "graphdb.fullname.configmap.properties" . }}
  labels:
    {{- include "graphdb.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- tpl ( toYaml . ) $ | nindent 4 }}
  {{- end }}
data:
  {{ .Values.configuration.properties.configmapKey }}: |-
    {{- tpl ( .Files.Get "files/config/graphdb.properties" ) . | nindent 4 }}
{{- end }}
