apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "graphdb.fullname.configmap.properties" . }}
  namespace: {{ include "graphdb.namespace" . }}
  labels:
    {{- include "graphdb.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
data:
  graphdb.properties: |-
    {{- tpl (.Files.Get "files/config/graphdb.properties" | trim) . | nindent 4 }}
    {{- if .Values.configuration.properties }}
    ##### Overrides from values.yaml #####
    {{- range $key, $val := .Values.configuration.properties -}}
    {{- if ne $val nil }}
    {{ $key }}={{ tpl ($val | toString) $ | quote }}
    {{- end }}
    {{- end -}}
    {{- end -}}
