apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "graphdb.fullname" . }}
  namespace: {{ include "graphdb.namespace" . }}
  labels:
    {{- include "graphdb.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
data:
  GDB_JAVA_OPTS: >-
    -Dgraphdb.home=/opt/graphdb/home
    -Denable-context-index=true
    -Dentity-pool-implementation=transactional
    -Dhealth.max.query.time.seconds=60
    {{ .Values.configuration.javaArguments }}
