{{- if and .Values.security.enabled (not .Values.initialConfiguration.users.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "graphdb.fullname.secret.users" . }}
  labels:
    {{- include "graphdb.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- tpl ( toYaml . ) $ | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{ .Values.initialConfiguration.users.secretKey }}: {{ tpl ( .Files.Get "files/config/users.js" | trim ) . | b64enc | quote }}
{{- end }}
