apiVersion: v1
kind: Secret
metadata:
  name: {{ include "graphdb.fullname.secret.properties" . }}
  namespace: {{ include "graphdb.namespace" . }}
  labels:
    {{- include "graphdb.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  graphdb-secrets.properties: |-
    ##### GraphDB sensitive configurations #####
    {{- if and (gt (int .Values.replicas) 1) (not .Values.cluster.existingClusterSecret) }}
    graphdb.auth.token.secret={{ .Values.cluster.clusterSecret | quote }}
    {{- end }}
    {{- if .Values.configuration.secretProperties }}
    ##### Secrets overrides from values.yaml #####
    {{- range $key, $val := .Values.configuration.secretProperties -}}
    {{- if ne $val nil }}
    {{ $key }}={{ tpl ($val | toString) $ | quote }}
    {{- end }}
    {{- end -}}
    {{- end -}}
