apiVersion: v1
kind: Service
metadata:
  name: {{ include "graphdb.fullname.service.headless" . }}
  labels:
    {{- include "graphdb.labels" . | nindent 4 }}
    {{- with .Values.graphdb.node.headlessService.labels }}
      {{- tpl ( toYaml . ) $ | nindent 4 }}
    {{- end }}
  {{- with (mergeOverwrite (deepCopy .Values.annotations) .Values.graphdb.node.headlessService.annotations) }}
  annotations:
    {{- tpl ( toYaml . ) $ | nindent 4 }}
  {{- end }}
spec:
  clusterIP: None
  selector:
    {{- include "graphdb.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.graphdb.node.headlessService.ports.http }}
      targetPort: http
      protocol: TCP
    {{- if gt (int $.Values.graphdb.clusterConfig.nodesCount) 1 }}
    - name: rpc
      port: {{ .Values.graphdb.node.headlessService.ports.rpc }}
      targetPort: rpc
      protocol: TCP
    {{- end }}
