{{- if .Values.graphdb.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "graphdb.serviceAccountName" . }}
  labels:
    {{- include "graphdb.labels" . | nindent 4 }}
  {{- with .Values.graphdb.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
