{{- if .Values.graphdb.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "graphdb.serviceAccountName" . }}
  labels:
    {{- include "graphdb.labels" . | nindent 4 }}
  {{- with (mergeOverwrite (deepCopy .Values.annotations) .Values.graphdb.serviceAccount.annotations) }}
  annotations:
    {{- tpl ( toYaml . ) $ | nindent 4 }}
  {{- end -}}
{{- end }}
