apiVersion: v1
kind: Service
metadata:
  name: graphdb-node
  labels:
    app: graphdb-node
    {{- include "graphdb.labels" . | nindent 4 }}
  {{- with .Values.graphdb.node.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  clusterIP: None
  selector:
    app: graphdb-node
  ports:
    - name: graphdb
      port: 7200
      targetPort: 7200
      protocol: TCP
    {{- if gt (int $.Values.graphdb.clusterConfig.nodesCount) 1 }}
    - name: rpc
      port: 7300
      targetPort: 7300
      protocol: TCP
    {{- end }}
