apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "graphdb.fullname" . }}
  labels:
    {{- include "graphdb.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- tpl ( toYaml . ) $ | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicas }}
  serviceName: {{ include "graphdb.fullname.service.headless" . }}
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "graphdb.selectorLabels" . | nindent 6 }}
  {{- if or .Values.persistence.enabled .Values.import.volumeMount.enabled }}
  volumeClaimTemplates:
    {{- if .Values.persistence.enabled }}
    - metadata:
        name: graphdb-storage
      spec:
        {{- toYaml .Values.persistence.volumeClaimTemplateSpec | nindent 8 }}
    {{- end }}
    {{- if .Values.import.volumeMount.enabled }}
    - metadata:
        name: graphdb-import
      spec:
        {{- toYaml .Values.import.volumeMount.volumeClaimTemplateSpec | nindent 8 }}
    {{- end }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "graphdb.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
          {{- tpl ( toYaml . ) $ | nindent 8 }}
        {{- end }}
      annotations:
        checksum/configmap: {{ include (print .Template.BasePath "/graphdb/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
          {{- tpl ( toYaml . ) $ | nindent 8 }}
        {{- end }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      serviceAccountName: {{ include "graphdb.serviceAccountName" . }}
      volumes:
        - name: graphdb-properties
          configMap:
            name: {{ .Values.configuration.propertiesConfig.existingConfigmap | default ( include "graphdb.fullname.configmap.properties" . ) }}
        - name: graphdb-logback-config
          configMap:
            name: {{ .Values.configuration.propertiesConfig.existingConfigmap | default ( include "graphdb.fullname.configmap.logback" . ) }}
        {{- if .Values.license.existingSecret }}
        - name: graphdb-license
          secret:
            secretName: {{ .Values.license.existingSecret }}
        {{- end }}
        {{- if or .Values.security.enabled .Values.configuration.initialSettingsConfig.existingConfigmap }}
        - name: graphdb-initial-settings-config
          configMap:
            name: {{ .Values.configuration.initialSettingsConfig.existingConfigmap | default ( include "graphdb.fullname.configmap.settings" . ) }}
        {{- end }}
        {{- if or .Values.security.enabled .Values.security.initialUsersConfig.existingConfigmap }}
        - name: graphdb-initial-users-config
          configMap:
            name: {{ .Values.security.initialUsersConfig.existingConfigmap | default ( include "graphdb.fullname.configmap.users" . ) }}
        {{- end }}
        {{- with .Values.extraVolumes }}
          {{- tpl ( toYaml . ) $ | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if or .Values.global.imagePullSecrets .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- include "graphdb.combinedImagePullSecrets" . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ include "graphdb.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.command }}
          command: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.args }}
          args: {{ toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPorts.http }}
            {{- if gt (int (.Values.replicas)) 1 }}
            - name: rpc
              containerPort: {{ .Values.containerPorts.rpc }}
            {{- end }}
            {{- with .Values.extraContainerPorts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "graphdb.fullname" . }}
            {{- with .Values.extraEnvFrom }}
              {{- tpl ( toYaml . ) $ | nindent 12 }}
            {{- end }}
          {{- with .Values.extraEnv }}
          env: {{- tpl ( toYaml . ) $ | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- if .Values.persistence.enabled }}
            - name: graphdb-storage
              mountPath: /opt/graphdb/home
            {{- end }}
            - name: graphdb-logback-config
              mountPath: /opt/graphdb/home/conf/logback.xml
              subPath: {{ .Values.configuration.logbackConfig.configmapKey }}
            {{- if .Values.license.existingSecret }}
            - name: graphdb-license
              mountPath: /opt/graphdb/home/conf/graphdb.license
              subPath: {{ .Values.license.licenseFilename }}
            {{- end }}
            {{- if .Values.import.volumeMount.enabled }}
            - name: graphdb-server-import
              mountPath: /opt/graphdb/home/graphdb-import
            {{- end }}
            {{- with .Values.extraVolumeMounts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.resources }}
          resources: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.securityContext }}
          securityContext: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.startupProbe }}
          startupProbe: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe: {{- toYaml . | nindent 12 }}
          {{- end }}
      initContainers:
        # PROVISION SETTINGS AND SECURITY
        - name: {{ .Chart.Name }}-provision-settings
          image: {{ include "graphdb.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: GRAPHDB_PUBLIC_URL
              value: {{ .Values.configuration.externalUrl }}
            - name: GRAPHDB_HTTP_PORT
              value: {{ .Values.containerPorts.http | quote }}
            - name: GRAPHDB_RPC_PORT
              value: {{ .Values.containerPorts.rpc | quote }}
          volumeMounts:
            {{- if .Values.persistence.enabled }}
            - name: graphdb-storage
              mountPath: /opt/graphdb/home
            {{- end }}
            - name: graphdb-properties
              mountPath: /tmp/graphdb/graphdb.properties
              subPath: {{ .Values.configuration.propertiesConfig.configmapKey }}
            {{- if or .Values.security.enabled .Values.configuration.initialSettingsConfig.existingConfigmap }}
            - name: graphdb-initial-settings-config
              mountPath: /tmp/graphdb/settings.js
              subPath: {{ .Values.configuration.initialSettingsConfig.configmapKey }}
            {{- end }}
            {{- if or .Values.security.enabled .Values.security.initialUsersConfig.existingConfigmap }}
            - name: graphdb-initial-users-config
              mountPath: /tmp/graphdb/users.js
              subPath: {{ .Values.security.initialUsersConfig.configmapKey }}
            {{- end }}
          {{- with .Values.initContainerSecurityContext }}
          securityContext: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.initContainerResources }}
          resources: {{ toYaml . | nindent 12 }}
          {{- end }}
          command: [ 'sh', '-c' ]
          args:
            - |
              set -eu
              mkdir -p /opt/graphdb/home/conf/ /opt/graphdb/home/data/ /opt/graphdb/home/jdbc-driver/

              echo 'Configuring graphdb.properties'
              cat /tmp/graphdb/graphdb.properties > /opt/graphdb/home/conf/graphdb.properties
              echo "" >> /opt/graphdb/home/conf/graphdb.properties
              echo "##### Overrides from initContainer #####" >> /opt/graphdb/home/conf/graphdb.properties

              echo "Configuring GraphDB hostname: $(hostname --fqdn)"
              echo "graphdb.vhosts=$(hostname --fqdn):${GRAPHDB_HTTP_PORT}, ${GRAPHDB_PUBLIC_URL}" >> /opt/graphdb/home/conf/graphdb.properties
              echo "graphdb.hostname=$(hostname --fqdn)" >> /opt/graphdb/home/conf/graphdb.properties
              echo "graphdb.rpc.address=$(hostname --fqdn):${GRAPHDB_RPC_PORT}" >> /opt/graphdb/home/conf/graphdb.properties

              if [[ ! -f /opt/graphdb/home/work/workbench/settings.js && ! -f /opt/graphdb/home/data/users.js && -f /tmp/graphdb/users.js ]]; then
                echo "Provisioning users with users.js file..."
                cp /tmp/graphdb/users.js /opt/graphdb/home/data/users.js
              fi

              if [[ ! -f /opt/graphdb/home/work/workbench/settings.js && ! -f /opt/graphdb/home/data/settings.js && -f /tmp/graphdb/settings.js ]]; then
                echo "Provisioning settings with settings.js file..."
                cp /tmp/graphdb/settings.js /opt/graphdb/home/data/settings.js
              fi

              echo 'Done'
        {{- with .Values.extraInitContainers }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
