apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "graphdb.fullname" . }}
  labels:
    {{- include "graphdb.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- tpl ( toYaml . ) $ | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ $.Values.graphdb.clusterConfig.nodesCount }}
  serviceName: {{ include "graphdb.fullname.service.headless" . }}
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  revisionHistoryLimit: {{ .Values.graphdb.node.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "graphdb.selectorLabels" . | nindent 6 }}
  {{- if or .Values.graphdb.node.persistence.enabled .Values.graphdb.import_directory_mount.enabled }}
  volumeClaimTemplates:
    {{- if .Values.graphdb.node.persistence.enabled }}
    - metadata:
        name: graphdb-storage
      spec:
        {{- toYaml .Values.graphdb.node.persistence.volumeClaimTemplateSpec | nindent 8 }}
    {{- end }}
    {{- if $.Values.graphdb.import_directory_mount.enabled }}
    - metadata:
        name: graphdb-import
      spec:
        {{- toYaml .Values.graphdb.import_directory_mount.volumeClaimTemplateSpec | nindent 8 }}
    {{- end }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "graphdb.selectorLabels" . | nindent 8 }}
        {{- with .Values.graphdb.node.podLabels }}
          {{- tpl ( toYaml . ) $ | nindent 8 }}
        {{- end }}
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/graphdb/configmap.yaml") . | sha256sum }}
        {{- with .Values.graphdb.node.podAnnotations }}
          {{- tpl ( toYaml . ) $ | nindent 8 }}
        {{- end }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.graphdb.node.terminationGracePeriodSeconds }}
      serviceAccountName: {{ include "graphdb.serviceAccountName" . }}
      volumes:
        - name: graphdb-properties
          configMap:
            name: {{ .Values.configuration.properties.existingConfigmap | default ( include "graphdb.fullname.configmap.properties" . ) }}
        - name: graphdb-logback-config
          configMap:
            name: {{ .Values.configuration.logback.existingConfigmap | default ( include "graphdb.fullname.configmap.logback" . ) }}
        {{- if .Values.graphdb.node.license }}
        - name: graphdb-license
          secret:
            secretName: {{ .Values.graphdb.node.license }}
        {{- end }}
        {{- if or .Values.graphdb.security.enabled .Values.provision.settings.existingConfigmap }}
        - name: graphdb-initial-settings-config
          configMap:
            name: {{ .Values.provision.settings.existingConfigmap | default ( include "graphdb.fullname.configmap.settings" . ) }}
        {{- end }}
        {{- if or .Values.graphdb.security.enabled .Values.provision.users.existingConfigmap }}
        - name: graphdb-initial-users-config
          configMap:
            name: {{ .Values.provision.users.existingConfigmap | default ( include "graphdb.fullname.configmap.users" . ) }}
        {{- end }}
        {{- with $.Values.graphdb.node.extraVolumes }}
          {{- tpl ( toYaml . ) $ | nindent 8 }}
        {{- end }}
      {{- with .Values.graphdb.node.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.graphdb.node.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.graphdb.node.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.graphdb.node.topologySpreadConstraints }}
      topologySpreadConstraints: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.graphdb.node.podSecurityContext }}
      securityContext: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if or .Values.global.imagePullSecrets .Values.deployment.imagePullSecrets }}
      imagePullSecrets:
        {{- include "graphdb.combinedImagePullSecrets" . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ include "graphdb.image" . }}
          imagePullPolicy: {{ $.Values.deployment.imagePullPolicy }}
          {{- with .Values.graphdb.node.command }}
          command: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.graphdb.node.args }}
          args: {{ toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPorts.http }}
            {{- if gt (int (.Values.graphdb.clusterConfig.nodesCount)) 1 }}
            - name: rpc
              containerPort: {{ .Values.containerPorts.rpc }}
            {{- end }}
            {{- with .Values.extraContainerPorts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "graphdb.fullname" . }}
            {{- with $.Values.graphdb.node.extraEnvFrom }}
              {{- tpl ( toYaml . ) $ | nindent 12 }}
            {{- end }}
          {{- with .Values.graphdb.node.extraEnv }}
          env: {{- tpl ( toYaml . ) $ | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- if .Values.graphdb.node.persistence.enabled }}
            - name: graphdb-storage
              mountPath: /opt/graphdb/home
            {{- end }}
            - name: graphdb-logback-config
              mountPath: /opt/graphdb/home/conf/logback.xml
              subPath: {{ .Values.configuration.logback.configmapKey }}
            {{- if .Values.graphdb.node.license }}
            - name: graphdb-license
              mountPath: /opt/graphdb/home/conf/graphdb.license
              subPath: {{ .Values.graphdb.node.licenseFilename }}
            {{- end }}
            {{- if $.Values.graphdb.import_directory_mount.enabled }}
            - name: graphdb-server-import
              mountPath: /opt/graphdb/home/graphdb-import
            {{- end }}
            {{- with $.Values.graphdb.node.extraVolumeMounts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.graphdb.node.resources }}
          resources: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.graphdb.node.securityContext }}
          securityContext: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.graphdb.node.startupProbe }}
          startupProbe: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.graphdb.node.readinessProbe }}
          readinessProbe: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.graphdb.node.livenessProbe }}
          livenessProbe: {{- toYaml . | nindent 12 }}
          {{- end }}
      initContainers:
        # PROVISION SETTINGS AND SECURITY
        - name: {{ .Chart.Name }}-provision-settings
          image: {{ include "graphdb.image" . }}
          imagePullPolicy: {{ $.Values.deployment.imagePullPolicy }}
          env:
            - name: GRAPHDB_PUBLIC_URL
              value: {{ include "graphdb.url.public" . }}
            - name: GRAPHDB_HTTP_PORT
              value: {{ .Values.containerPorts.http | quote }}
            - name: GRAPHDB_RPC_PORT
              value: {{ .Values.containerPorts.rpc | quote }}
          volumeMounts:
            {{- if .Values.graphdb.node.persistence.enabled }}
            - name: graphdb-storage
              mountPath: /opt/graphdb/home
            {{- end }}
            - name: graphdb-properties
              mountPath: /tmp/graphdb/graphdb.properties
              subPath: {{ .Values.configuration.properties.configmapKey }}
            {{- if or .Values.graphdb.security.enabled .Values.provision.settings.existingConfigmap }}
            - name: graphdb-initial-settings-config
              mountPath: /tmp/graphdb/settings.js
              subPath: {{ .Values.provision.settings.configmapKey }}
            {{- end }}
            {{- if or .Values.graphdb.security.enabled .Values.provision.settings.existingConfigmap }}
            - name: graphdb-initial-users-config
              mountPath: /tmp/graphdb/users.js
              subPath: {{ .Values.provision.users.configmapKey }}
            {{- end }}
          {{- with .Values.graphdb.node.initContainerSecurityContext }}
          securityContext: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.graphdb.node.initContainerResources }}
          resources: {{ toYaml . | nindent 12 }}
          {{- end }}
          command: [ 'sh', '-c' ]
          args:
            - |
              set -eu
              mkdir -p /opt/graphdb/home/conf/ /opt/graphdb/home/data/ /opt/graphdb/home/jdbc-driver/

              echo 'Configuring graphdb.properties'
              cat /tmp/graphdb/graphdb.properties > /opt/graphdb/home/conf/graphdb.properties
              echo "" >> /opt/graphdb/home/conf/graphdb.properties
              echo "##### Overrides from initContainer #####" >> /opt/graphdb/home/conf/graphdb.properties

              echo "Configuring GraphDB hostname: $(hostname --fqdn)"
              echo "graphdb.vhosts=$(hostname --fqdn):${GRAPHDB_HTTP_PORT}, ${GRAPHDB_PUBLIC_URL}" >> /opt/graphdb/home/conf/graphdb.properties
              echo "graphdb.hostname=$(hostname --fqdn)" >> /opt/graphdb/home/conf/graphdb.properties
              echo "graphdb.rpc.address=$(hostname --fqdn):${GRAPHDB_RPC_PORT}" >> /opt/graphdb/home/conf/graphdb.properties

              if [[ ! -f /opt/graphdb/home/work/workbench/settings.js && ! -f /opt/graphdb/home/data/users.js && -f /tmp/graphdb/users.js ]]; then
                echo "Provisioning users with users.js file..."
                cp /tmp/graphdb/users.js /opt/graphdb/home/data/users.js
              fi

              if [[ ! -f /opt/graphdb/home/work/workbench/settings.js && ! -f /opt/graphdb/home/data/settings.js && -f /tmp/graphdb/settings.js ]]; then
                echo "Provisioning settings with settings.js file..."
                cp /tmp/graphdb/settings.js /opt/graphdb/home/data/settings.js
              fi

              echo 'Done'
        {{- with .Values.graphdb.node.extraInitContainers }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
