
fullnameOverride: graphdb

# Cluster requires license, you have to provision it before deploying this chart
license:
  existingSecret: graphdb-license

replicas: 3

configuration:
  externalUrl: https://graphdb.apps-crc.testing

ingress:
  enabled: false

# OpenShift uses very high uid/gid, override the default with 1000660000
podSecurityContext:
  runAsUser: 1000660000
  runAsGroup: 1000660000
  fsGroup: 1000660000

jobs:
  podSecurityContext:
    runAsUser: 1000660000
    runAsGroup: 1000660000
    fsGroup: 1000660000

proxy:
  fullnameOverride: graphdb-proxy

  podSecurityContext:
    runAsUser: 1000660000
    runAsGroup: 1000660000
    fsGroup: 1000660000
