# This example shows how to deploy and expose GraphDB with AWS Load Balancer Controller Ingress with SSL enabled.

configuration:
  externalUrl: https://graphdb-example-dns-name.com/ # Change this to your ALB DNS name or Route53 if you use it.

ingress:
  enabled: true
  className: alb
  annotations:
   alb.ingress.kubernetes.io/load-balancer-name: graphdb-ingress
   alb.ingress.kubernetes.io/target-type: ip
   alb.ingress.kubernetes.io/scheme: internet-facing
   alb.ingress.kubernetes.io/inbound-cidrs: "0.0.0.0/0"
   alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
   alb.ingress.kubernetes.io/certificate-arn: "" # ARN of the ACM SSL Certificate that will be used
   alb.ingress.kubernetes.io/ssl-policy: "ELBSecurityPolicy-TLS13-1-2-2021-06"
   alb.ingress.kubernetes.io/ssl-redirect: '443'
