# This example shows how to configure and deploy GraphDB with cluster TLS authentication using
# existing keystore and the default java trust store
configuration:
  # change these variables to match the correct values for your setup
  javaArguments: >-
    -Dgraphdb.raft.security.mode=TLS
    -Dgraphdb.raft.security.rootCerts=
    -Dgraphdb.raft.security.keyAlias=
    -Dgraphdb.raft.security.keystoreFile=
    -Dgraphdb.raft.security.keystorePass=
extraVolumes:
  - name: rootCerts-volume
    secret:
      secretName: my-root-certs-secret # Change this to the secret that contains your trusted root certificates
  - name: keystore-volume
    secret:
      secretName: my-keystore-secret # Change this to the secret that contains your keystore
extraVolumeMounts:
  - name: rootCerts-volume
    mountPath: /opt/graphdb/home/rootCerts.pem # Change this to the path where you want to mount the trusted root certificates
    subPath: rootCerts.pem
  - name: keystore-volume
    mountPath: /opt/graphdb/home/mykeystore.jks # Change this to the path where you want to mount the keystore
    subPath: mykeystore.jks
