apiVersion: v1
kind: ConfigMap
metadata:
  name: graphdb-custom-logback-config
data:
  logback.xml: |-
    <configuration debug="false" scan="true" scanPeriod="30 seconds">
        <jmxConfigurator/>

        <if condition='p("logDestinationDirectory").isEmpty()'>
            <then>
                <if condition='!p("catalina.base").isEmpty()'>
                    <then>
                        <property name="logDestinationDirectory" value="${catalina.base}/logs/graphdb"/>
                    </then>
                    <else>
                        <if condition='!p("jetty.base").isEmpty()'>
                            <then>
                                <property name="logDestinationDirectory" value="${jetty.base}/logs/graphdb"/>
                            </then>
                            <else>
                                <property name="logDestinationDirectory" value="logs"/>
                            </else>
                        </if>
                    </else>
                </if>
            </then>
        </if>

        <property name="defaultPattern" value="[%-5p] %d{ISO8601} [%t | %c{5}]%X{headers} %m%n%ex"/>
        <property name="encoding" value="UTF-8"/>

        <property name="keepLogDays" value="30"/>
        <property name="logMaxSize" value="0"/>
        <property name="maxFileSize" value="1GB"/>

        <appender name="AuditLog" class="ch.qos.logback.core.rolling.RollingFileAppender">
            <file>${logDestinationDirectory}/audit.log</file>
            <rollingPolicy class="ch.qos.logback.core.rolling.SizeAndTimeBasedRollingPolicy">
                <fileNamePattern>${logDestinationDirectory}/audit-%d{yyyy-MM}/audit-%d{yyyy-MM-dd}.%i.zip</fileNamePattern>
                <maxFileSize>${maxFileSize}</maxFileSize>
                <maxHistory>${keepLogDays}</maxHistory>
                <totalSizeCap>${logMaxSize}</totalSizeCap>
                <cleanHistoryOnStart>true</cleanHistoryOnStart>
            </rollingPolicy>
            <encoder>
                <pattern>${defaultPattern}</pattern>
                <charset>${encoding}</charset>
            </encoder>
        </appender>

        <appender name="MainLog" class="ch.qos.logback.core.rolling.RollingFileAppender">
            <file>${logDestinationDirectory}/main.log</file>
            <rollingPolicy class="ch.qos.logback.core.rolling.SizeAndTimeBasedRollingPolicy">
                <fileNamePattern>${logDestinationDirectory}/main-%d{yyyy-MM}/main-%d{yyyy-MM-dd}.%i.zip
                </fileNamePattern>
                <maxFileSize>${maxFileSize}</maxFileSize>
                <maxHistory>${keepLogDays}</maxHistory>
                <totalSizeCap>${logMaxSize}</totalSizeCap>
                <cleanHistoryOnStart>true</cleanHistoryOnStart>
            </rollingPolicy>
            <encoder>
                <pattern>${defaultPattern}</pattern>
                <charset>${encoding}</charset>
            </encoder>
        </appender>

        <appender name="ErrorLog" class="ch.qos.logback.core.rolling.RollingFileAppender">
            <file>${logDestinationDirectory}/error.log</file>
            <rollingPolicy class="ch.qos.logback.core.rolling.SizeAndTimeBasedRollingPolicy">
                <fileNamePattern>${logDestinationDirectory}/errors-%d{yyyy-MM}/error-%d{yyyy-MM-dd}.%i.zip
                </fileNamePattern>
                <maxFileSize>${maxFileSize}</maxFileSize>
                <maxHistory>${keepLogDays}</maxHistory>
                <totalSizeCap>${logMaxSize}</totalSizeCap>
                <cleanHistoryOnStart>true</cleanHistoryOnStart>
            </rollingPolicy>
            <encoder>
                <pattern>${defaultPattern}</pattern>
                <charset>${encoding}</charset>
            </encoder>
            <filter class="ch.qos.logback.classic.filter.ThresholdFilter">
                <level>ERROR</level>
            </filter>
        </appender>

        <appender name="QueryLog" class="ch.qos.logback.core.rolling.RollingFileAppender">
            <file>${logDestinationDirectory}/query.log</file>
            <rollingPolicy class="ch.qos.logback.core.rolling.SizeAndTimeBasedRollingPolicy">
                <fileNamePattern>${logDestinationDirectory}/queries-%d{yyyy-MM}/query-%d{yyyy-MM-dd}.%i.zip</fileNamePattern>
                <maxFileSize>${maxFileSize}</maxFileSize>
                <maxHistory>${keepLogDays}</maxHistory>
                <totalSizeCap>${logMaxSize}</totalSizeCap>
                <cleanHistoryOnStart>true</cleanHistoryOnStart>
            </rollingPolicy>
            <encoder>
                <pattern>${defaultPattern}</pattern>
                <charset>${encoding}</charset>
            </encoder>
        </appender>

        <appender name="SlowQueryLog" class="ch.qos.logback.core.rolling.RollingFileAppender">
            <file>${logDestinationDirectory}/slow-query.log</file>
            <rollingPolicy class="ch.qos.logback.core.rolling.SizeAndTimeBasedRollingPolicy">
                <fileNamePattern>${logDestinationDirectory}/slow-queries-%d{yyyy-MM}/slow-query-%d{yyyy-MM-dd}.%i.zip</fileNamePattern>
                <maxFileSize>${maxFileSize}</maxFileSize>
                <maxHistory>${keepLogDays}</maxHistory>
                <totalSizeCap>${logMaxSize}</totalSizeCap>
                <cleanHistoryOnStart>true</cleanHistoryOnStart>
            </rollingPolicy>
            <encoder>
                <pattern>${defaultPattern}</pattern>
                <charset>${encoding}</charset>
            </encoder>
        </appender>

        <if condition='!p("graphdb.foreground").isEmpty()'>
            <then>
                <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
                    <encoder>
                        <pattern>${defaultPattern}</pattern>
                    </encoder>
                </appender>
            </then>
        </if>

        <!-- Adjust logger levels for detailed trace logging -->
        <logger name="com.ontotext.forest.security.audit.AuditLoggingFilter" level="TRACE" additivity="false">
            <appender-ref ref="AuditLog"/>
        </logger>

        <logger name="com.ontotext.trree.monitorRepository.MonitorRepositoryConnection" level="TRACE" additivity="false">
            <appender-ref ref="QueryLog"/>
        </logger>

        <logger name="com.ontotext.trree.query.LoggingClosableIteration" level="TRACE" additivity="false">
            <appender-ref ref="QueryLog"/>
        </logger>

        <logger name="slow-queries" level="TRACE" additivity="false">
            <appender-ref ref="SlowQueryLog"/>
        </logger>

        <root>
            <level value="${graphdb.logger.root.level:-TRACE}"/> <!-- Change root level to TRACE -->
            <appender-ref ref="MainLog"/>
            <appender-ref ref="ErrorLog"/>
            <if condition='!p("graphdb.foreground").isEmpty()'>
                <then>
                    <appender-ref ref="STDOUT"/>
                </then>
            </if>
        </root>

        <logger name="org.springframework" level="WARN"/>
        <logger name="org.apache" level="WARN"/>
        <logger name="com.github.ziplet" level="WARN"/>
        <logger name="springfox.documentation" level="WARN"/>
        <logger name="org.eclipse.rdf4j.query.algebra.evaluation" level="ERROR"/>

        <logger name="hsqldb.*" level="WARN"/>
        <logger name="org.geotoolkit.*" level="WARN"/>
        <logger name="pitt.search.semanticvectors.DocVectors" level="WARN"/>
    </configuration>

