apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
    - image: busybox
      command:
        - sleep
        - "3600"
      imagePullPolicy: IfNotPresent
      name: busybox
  restartPolicy: Always
---
apiVersion: {{ $.Values.versions.deployment }}
kind: Deployment
metadata:
  name: browser
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: firefox
  replicas: 1
  template:
    metadata:
      labels:
        app: firefox
    spec:
      containers:
        - name: firefox
          image: selenoid/vnc_firefox:97.0
          ports:
            - name: vnc-port
              containerPort: 4444
            - name: user-interface
              containerPort: 8080
          env:
            - name: ENABLE_VNC
              value: "true"

---
apiVersion: v1
kind: Service
metadata:
  name: browser-svc
  labels:
    app: firefox
spec:
  ports:
    - port: 4444
      protocol: TCP
      name: vnc-port
    - port: 8080
      name: user-interface
  selector:
    app: firefox
  type: NodePort
