# Loop over the replica count
{{ range $i, $master_index := untilStep 1 (add1 $.Values.graphdb.clusterConfig.mastersCount | int ) 1 }}

{{ $worker_endpoint := printf "http://graphdb-master-%d:7200" $master_index }}
{{- $authToken := ((printf "%s:%s" $.Values.graphdb.security.provisioningUsername $.Values.graphdb.security.provisioningPassword) | b64enc) }}

---
apiVersion: {{ $.Values.versions.statefulset }}
kind: StatefulSet
metadata:
  name: graphdb-master-{{ $master_index }}
  labels:
    app: graphdb-master-{{ $master_index }}
spec:
  replicas: 1
  serviceName: graphdb-master-{{ $master_index }}
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: graphdb-master-{{ $master_index }}
  {{- if or (hasKey $.Values.graphdb.masters.persistence "volumeClaimTemplateSpec") (include "shouldRenderBackupVolumeClaimTemplate" (dict "backupRestore" $.Values.graphdb.backupRestore "master_index" $master_index)) }}
  volumeClaimTemplates:
  {{- end }}
    {{- if hasKey $.Values.graphdb.masters.persistence "volumeClaimTemplateSpec" }}
    - metadata:
        name: graphdb-master-{{ $master_index }}-data-dynamic-pvc
      spec: {{ toYaml $.Values.graphdb.masters.persistence.volumeClaimTemplateSpec | nindent 8 }}
    {{- end }}
    {{- if (include "shouldRenderBackupVolumeClaimTemplate" (dict "backupRestore" $.Values.graphdb.backupRestore "master_index" $master_index)) }}
    - metadata:
        name: graphdb-backup-pvc
      spec: {{ toYaml $.Values.graphdb.backupRestore.persistence.volumeClaimTemplateSpec | nindent 8 }}
    {{- end }}
  template:
    metadata:
      labels:
        app: graphdb-master-{{ $master_index }}
    spec:
      terminationGracePeriodSeconds: 60
      volumes:
        - name: graphdb-master-license
          secret:
            secretName: {{ default $.Values.graphdb.masters.license (include "resolveMasterValue" (dict "nodes" $.Values.graphdb.masters.nodes "value_name" "license" "master_index" $master_index)) }}
        {{- if not (hasKey $.Values.graphdb.masters.persistence "volumeClaimTemplateSpec") }}
        - name: graphdb-master-storage
          persistentVolumeClaim:
            claimName: graphdb-master-{{ $master_index }}-data-pvc
        {{- end }}
        - name: graphdb-master-repo-config
          configMap:
            name: {{ required "Config map with .ttl for repositories creation is required!" $.Values.graphdb.masters.repositoryConfigmap }}
        - name: graphdb-master-settings-config
          configMap:
            name: {{ required "Config map with settings.js (and graphdb.properties(optional) ) for security/settings provisioning is required!" $.Values.graphdb.masters.settingsConfigmap }}
      {{ if hasKey $.Values.deployment "imagePullSecret" }}
      imagePullSecrets:
        - name: {{ $.Values.deployment.imagePullSecret }}
      {{ end }}
      nodeSelector:
        {{- default "{}" (default ($.Values.graphdb.masters.nodeSelector | toYaml) (include "resolveMasterValue" (dict "nodes" $.Values.graphdb.masters.nodes "value_name" "nodeSelector" "master_index" $master_index))) | nindent 8  }}
      affinity:
        {{- default "{}" (default ($.Values.graphdb.masters.affinity | toYaml) (include "resolveMasterValue" (dict "nodes" $.Values.graphdb.masters.nodes "value_name" "affinity" "master_index" $master_index))) | nindent 8  }}
      tolerations:
        {{- default "{}" (default ($.Values.graphdb.masters.tolerations | toYaml) (include "resolveMasterValue" (dict "nodes" $.Values.graphdb.masters.nodes "value_name" "tolerations" "master_index" $master_index))) | nindent 8  }}
      topologySpreadConstraints:
        {{- default "{}" (default ($.Values.graphdb.masters.topologySpreadConstraints | toYaml) (include "resolveMasterValue" (dict "nodes" $.Values.graphdb.masters.nodes "value_name" "topologySpreadConstraints" "master_index" $master_index))) | nindent 8  }}
      containers:
        - name: graphdb-master-{{ $master_index }}
          image: {{ $.Values.images.graphdb }}
          imagePullPolicy: {{ $.Values.deployment.imagePullPolicy }}
          ports:
            - name: graphdb-m-{{ $master_index }}
              containerPort: 7200
          envFrom:
            - configMapRef:
                name: graphdb-master-{{ $master_index }}-configmap
          volumeMounts:
            {{- if hasKey $.Values.graphdb.masters.persistence "volumeClaimTemplateSpec" }}
            - name: graphdb-master-{{ $master_index }}-data-dynamic-pvc
            {{- else }}
            - name: graphdb-master-storage
            {{- end }}
              mountPath: /opt/graphdb/home
            {{- if and (eq ($master_index | int64) 1) (include "shouldRenderBackupVolumeClaimTemplate" (dict "backupRestore" $.Values.graphdb.backupRestore "master_index" $master_index)) }}
            - name: graphdb-backup-pvc
              mountPath: /opt/graphdb/backups
            {{- end }}
          resources: {{ $.Values.graphdb.masters.resources | toYaml | nindent 12 }}
          # Allow for GraphDB to start within 10*30 seconds before readiness & liveness probes interfere
          startupProbe:
            httpGet:
              path: /protocol
              port: graphdb-m-{{ $master_index }}
            failureThreshold: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /protocol
              port: graphdb-m-{{ $master_index }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /protocol
              port: graphdb-m-{{ $master_index }}
            initialDelaySeconds: 60
            periodSeconds: 10
      initContainers:
        # LICENSE PROVISION
        - name: provision-license
          image: {{ $.Values.images.busybox }}
          imagePullPolicy: {{ $.Values.deployment.imagePullPolicy }}
          volumeMounts:
            {{- if hasKey $.Values.graphdb.masters.persistence "volumeClaimTemplateSpec" }}
            - name: graphdb-master-{{ $master_index }}-data-dynamic-pvc
            {{- else }}
            - name: graphdb-master-storage
            {{- end }}
              mountPath: /opt/graphdb/home
            - name: graphdb-master-license
              mountPath: /tmp/license/
          command: ['sh', '-c']
          args:
            - |
                mkdir -p /opt/graphdb/home/conf/
                cd /opt/graphdb/home/conf/
                [ -f graphdb.license ] && echo "License present, exiting..." && exit 0

                echo 'Provisioning GraphDB master {{ $master_index }} license'
                cp /tmp/license/*.license ./graphdb.license
                echo 'Done'
        # REPO PROVISION
        - name: provision-repository
          image: {{ $.Values.images.busybox }}
          imagePullPolicy: {{ $.Values.deployment.imagePullPolicy }}
          volumeMounts:
            {{- if hasKey $.Values.graphdb.masters.persistence "volumeClaimTemplateSpec" }}
            - name: graphdb-master-{{ $master_index }}-data-dynamic-pvc
            {{- else }}
            - name: graphdb-master-storage
            {{- end }}
              mountPath: /opt/graphdb/home
            - name: graphdb-master-repo-config
              mountPath: /tmp/graphdb
          command: ['sh', '-c']
          args:
            - |
              set -eu
              for filename in /tmp/graphdb/*.ttl; do
                repositoryName=$(grep "rep:repositoryID" $filename | sed -ne 's/rep:repositoryID "//p' | sed -ne 's/" ;//p' | sed -ne 's/^[[:space:]]*//p')
                echo "Repo name: $repositoryName"
                echo "File name: $filename"
                mkdir -p /opt/graphdb/home/data/repositories/$repositoryName ;
                cd /opt/graphdb/home/data/repositories/$repositoryName ;

                # If the repo configuration exists -> skip provisioning
                [ -f config.ttl ] && echo "Repository $repositoryName exists, exiting..." && exit 0

                echo "Provisioning GraphDB $repositoryName repository with file $filename" ;
                cp $filename ./config.ttl ;
                echo 'Done'
              done
        # PROVISION SETTINGS AND SECURITY
        - name: provision-settings
          image: {{ $.Values.images.busybox }}
          imagePullPolicy: {{ $.Values.deployment.imagePullPolicy }}
          volumeMounts:
            {{- if hasKey $.Values.graphdb.masters.persistence "volumeClaimTemplateSpec" }}
            - name: graphdb-master-{{ $master_index }}-data-dynamic-pvc
            {{- else }}
            - name: graphdb-master-storage
            {{- end }}
              mountPath: /opt/graphdb/home
            - name: graphdb-master-settings-config
              mountPath: /tmp/graphdb
          command: ['sh', '-c']
          args:
            - |
              set -eu
              if [[ ! -f /opt/graphdb/home/work/workbench/settings.js && -f /tmp/graphdb/settings.js ]]; then
                echo "Provisioning users settings with settings.js file..."
                mkdir -p /opt/graphdb/home/work/workbench ;
                cp /tmp/graphdb/settings.js /opt/graphdb/home/work/workbench/settings.js
              fi
              if [[ ! -f /opt/graphdb/home/conf/graphdb.properties && -f /tmp/graphdb/graphdb.properties ]]; then
                echo "Provisioning graphdb properties file..."
                mkdir -p /opt/graphdb/home/conf ;
                cp /tmp/graphdb/graphdb.properties /opt/graphdb/home/conf/graphdb.properties
              fi
              echo 'Done'
        {{- if and (eq $.Values.graphdb.topology "standalone") (include "shouldRenderBackupVolumeClaimTemplate" (dict "backupRestore" $.Values.graphdb.backupRestore "master_index" $master_index)) }}
        - name: restore-standalone
          image: {{ $.Values.images.busybox }}
          imagePullPolicy: {{ $.Values.deployment.imagePullPolicy }}
          volumeMounts:
            - name: graphdb-master-storage
              mountPath: /opt/graphdb/
            - name: graphdb-backup-pvc
              mountPath: {{ $.Values.deployment.storage }}/graphdb-backups/
          command: ['sh', '-c']
          args:
            - |
              {{ $repo := $.Values.graphdb.backupRestore.restore_repository -}}
              mkdir -p /opt/graphdb/home/data/repositories/{{ $repo }} ;
              cd /opt/graphdb/home/data/repositories/ ;
              echo "Backup to restore: {{ $.Values.deployment.storage }}/graphdb-backups/backup/{{ $repo }}-{{ $.Values.graphdb.backupRestore.restore_from_backup }}/"
              if [ -d {{ $.Values.deployment.storage }}/graphdb-backups/backup/{{ $repo }}-{{ $.Values.graphdb.backupRestore.restore_from_backup }}/ ]; then
                rm -rf {{ $repo }}
                unzip {{ $.Values.deployment.storage }}/graphdb-backups/backup/{{ $repo }}-{{ $.Values.graphdb.backupRestore.restore_from_backup }}/*
                echo "Successfully restored!"
              else
                echo "Nothing to restore."
              fi
        {{- end }}

---
apiVersion: {{ $.Values.versions.service }}
kind: Service
metadata:
  name: graphdb-master-{{ $master_index }}
  labels:
    app: graphdb-master-{{ $master_index }}
spec:
  selector:
    app: graphdb-master-{{ $master_index }}
  ports:
    - name: graphdb-master-{{ $master_index }}
      port: 7200
      targetPort: 7200
      protocol: TCP
{{ end }}
