{{- $configs := ($.Values.graphdb.configs | default dict) }}
---
apiVersion: {{ $.Values.versions.statefulset }}
kind: StatefulSet
metadata:
  name: graphdb-node
  labels:
    app: graphdb-node
spec:
  replicas: {{ $.Values.graphdb.clusterConfig.nodesCount }}
  serviceName: graphdb-node
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: graphdb-node
  {{- if or (hasKey $.Values.graphdb.node.persistence "volumeClaimTemplateSpec") }}
  volumeClaimTemplates:
  {{- end }}
    {{- if hasKey $.Values.graphdb.node.persistence "volumeClaimTemplateSpec" }}
    - metadata:
        name: graphdb-node-data-dynamic-pvc
      {{- $spec := dict "globalStorageClassName" $.Values.global.storageClass "spec" $.Values.graphdb.node.persistence.volumeClaimTemplateSpec }}
      spec: {{ include "renderVolumeClaimTemplateSpec" $spec | nindent 8 }}
    {{- end }}
    {{- if $.Values.graphdb.import_directory_mount.enabled }}
    - metadata:
        name: graphdb-server-import-dir
      {{- $spec := dict "globalStorageClassName" $.Values.global.storageClass "spec" $.Values.graphdb.import_directory_mount.volumeClaimTemplateSpec }}
      spec: {{ include "renderVolumeClaimTemplateSpec" $spec | nindent 8 }}
    {{- end }}
  template:
    metadata:
      labels:
        app: graphdb-node
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/configuration/graphdb-node-configmap.yaml") . | sha256sum }}
    spec:
      setHostnameAsFQDN: true
      terminationGracePeriodSeconds: 120
      volumes:
        {{- if ne ($.Values.graphdb.node.license) "" }}
        - name: graphdb-license
          secret:
            secretName: {{ $.Values.graphdb.node.license }}
        {{- end }}
        {{- if not (hasKey $.Values.graphdb.node.persistence "volumeClaimTemplateSpec") }}
        - name: graphdb-node-storage
          persistentVolumeClaim:
            claimName: graphdb-node-data-pvc
        {{- end }}
        {{- if or $configs.settingsConfigMap $.Values.graphdb.security.enabled }}
        - name: graphdb-settings-config
          configMap:
            name: {{ $configs.settingsConfigMap | default "graphdb-settings-configmap" }}
        {{- end }}
        {{- if or $configs.usersConfigMap $.Values.graphdb.security.enabled }}
        - name: graphdb-users-config
          configMap:
            name: {{ $configs.usersConfigMap | default "graphdb-users-configmap" }}
        {{- end }}
        {{- if $configs.propertiesConfigMap }}
        - name: graphdb-properties-config
          configMap:
            name: {{ $configs.propertiesConfigMap }}
        {{- end }}
        {{- if $configs.logbackConfigMap }}
        - name: graphdb-logback-config
          configMap:
            name: {{ $configs.logbackConfigMap }}
        {{- end }}
      imagePullSecrets:
        {{- include "combinedImagePullSecrets" $ | nindent 8 }}
      containers:
        - name: graphdb-node
          image: {{ include "renderFullImageName" (dict "globalRegistry" $.Values.global.imageRegistry "image" $.Values.images.graphdb) }}
          imagePullPolicy: {{ $.Values.deployment.imagePullPolicy }}
          ports:
            - name: graphdb
              containerPort: 7200
              {{- if gt (int (.Values.graphdb.clusterConfig.nodesCount)) 1 }}
            - name: graphdb-rpc
              containerPort: 7300
              {{- end }}
          envFrom:
            - configMapRef:
                name: graphdb-node-configmap
          volumeMounts:
            {{- if hasKey $.Values.graphdb.node.persistence "volumeClaimTemplateSpec" }}
            - name: graphdb-node-data-dynamic-pvc
            {{- else }}
            - name: graphdb-node-storage
            {{- end }}
              mountPath: /opt/graphdb/home
            {{- if $.Values.graphdb.import_directory_mount.enabled }}
            - name: graphdb-server-import-dir
              mountPath: /opt/graphdb/home/graphdb-import
            {{- end }}
          resources: {{ $.Values.graphdb.node.resources | toYaml | nindent 12 }}
          # Allow for GraphDB to start within 10*30 seconds before readiness & liveness probes interfere
          startupProbe:
            httpGet:
              path: /protocol
              port: graphdb
            failureThreshold: 30
            timeoutSeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /protocol
              port: graphdb
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: {{ .Values.graphdb.node.livenessProbe.path }}
              port: {{ .Values.graphdb.node.livenessProbe.port }}
            initialDelaySeconds: {{ .Values.graphdb.node.livenessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.graphdb.node.livenessProbe.timeoutSeconds }}
            periodSeconds: {{ .Values.graphdb.node.livenessProbe.periodSeconds }}
      initContainers:
      {{- if ne ($.Values.graphdb.node.license) "" }}
        # LICENSE PROVISION
        - name: provision-license
          image: {{ include "renderFullImageName" (dict "globalRegistry" $.Values.global.imageRegistry "image" $.Values.images.busybox) }}
          imagePullPolicy: {{ $.Values.deployment.imagePullPolicy }}
          volumeMounts:
            {{- if hasKey $.Values.graphdb.node.persistence "volumeClaimTemplateSpec" }}
            - name: graphdb-node-data-dynamic-pvc
            {{- else }}
            - name: graphdb-node-storage
            {{- end }}
              mountPath: /opt/graphdb/home
            - name: graphdb-license
              mountPath: /tmp/license/
          command: ['sh', '-c']
          args:
            - |
              mkdir -p /opt/graphdb/home/conf/
              cd /opt/graphdb/home/conf/
              [ -f graphdb.license ] && rm graphdb.license

              echo 'Provisioning GraphDB node license'
              cp /tmp/license/*.license ./graphdb.license
              echo 'Done'
        {{- end }}
        # PROVISION SETTINGS AND SECURITY
        - name: provision-settings
          image: {{ include "renderFullImageName" (dict "globalRegistry" $.Values.global.imageRegistry "image" $.Values.images.busybox) }}
          imagePullPolicy: {{ $.Values.deployment.imagePullPolicy }}
          volumeMounts:
            {{- if hasKey $.Values.graphdb.node.persistence "volumeClaimTemplateSpec" }}
            - name: graphdb-node-data-dynamic-pvc
            {{- else }}
            - name: graphdb-node-storage
            {{- end }}
              mountPath: /opt/graphdb/home
            {{- if or $configs.settingsConfigMap $.Values.graphdb.security.enabled }}
            - name: graphdb-settings-config
              mountPath: /tmp/graphdb-settings-configmap
            {{- end }}
            {{- if or $configs.usersConfigMap $.Values.graphdb.security.enabled }}
            - name: graphdb-users-config
              mountPath: /tmp/graphdb-users-configmap
            {{- end }}
            {{- if $configs.propertiesConfigMap }}
            - name: graphdb-properties-config
              mountPath: /tmp/graphdb-properties-configmap
            {{- end }}
            {{- if $configs.logbackConfigMap }}
            - name: graphdb-logback-config
              mountPath: /tmp/graphdb-logback-configmap
            {{- end }}
          command: ['sh', '-c']
          args:
            - |
              set -eu
              if [[ ! -f /opt/graphdb/home/work/workbench/settings.js && ! -f /opt/graphdb/home/data/users.js && -f /tmp/graphdb-users-configmap/users.js ]]; then
                echo "Provisioning users with users.js file..."
                mkdir -p /opt/graphdb/data ;
                cp /tmp/graphdb-users-configmap/users.js /opt/graphdb/home/data/users.js
              fi
              if [[ ! -f /opt/graphdb/home/work/workbench/settings.js && ! -f /opt/graphdb/home/data/settings.js && -f /tmp/graphdb-settings-configmap/settings.js ]]; then
                echo "Provisioning settings with settings.js file..."
                mkdir -p /opt/graphdb/data ;
                cp /tmp/graphdb-settings-configmap/settings.js /opt/graphdb/data/settings.js
              fi
              if [[ ! -f /opt/graphdb/home/conf/graphdb.properties && -f /tmp/graphdb-properties-configmap/graphdb.properties ]]; then
                echo "Provisioning graphdb properties file..."
                mkdir -p /opt/graphdb/home/conf ;
                cp /tmp/graphdb-properties-configmap/graphdb.properties /opt/graphdb/home/conf/graphdb.properties
              fi
              if [[ ! -f /opt/graphdb/home/conf/logback.xml && -f /tmp/graphdb-logback-configmap/logback.xml ]]; then
                echo "Provisioning logging config file..."
                mkdir -p /opt/graphdb/home/conf ;
                cp /tmp/graphdb-logback-configmap/logback.xml /opt/graphdb/home/conf/logback.xml
              fi
              mkdir -p /opt/graphdb/home/jdbc-driver
              echo 'Done'

---
apiVersion: {{ $.Values.versions.service }}
kind: Service
metadata:
  name: graphdb-node
  labels:
    app: graphdb-node
spec:
  selector:
    app: graphdb-node
  ports:
    - name: graphdb
      port: 7200
      targetPort: 7200
      protocol: TCP
