{{- $configs := ($.Values.graphdb.configs | default dict) }}
---
apiVersion: {{ $.Values.versions.statefulset }}
kind: StatefulSet
metadata:
  name: graphdb-node
  labels: {{- include "graphdb.labels" . | nindent 4 }}
    app: graphdb-node
spec:
  replicas: {{ $.Values.graphdb.clusterConfig.nodesCount }}
  serviceName: graphdb-node
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: graphdb-node
  {{- if or (hasKey $.Values.graphdb.node.persistence "volumeClaimTemplateSpec") ($.Values.graphdb.import_directory_mount.enabled)}}
  volumeClaimTemplates:
    {{- if hasKey $.Values.graphdb.node.persistence "volumeClaimTemplateSpec" }}
    - metadata:
        name: graphdb-node-data-dynamic-pvc
      {{- $spec := dict "globalStorageClassName" $.Values.global.storageClass "spec" $.Values.graphdb.node.persistence.volumeClaimTemplateSpec }}
      spec: {{ include "renderVolumeClaimTemplateSpec" $spec | nindent 8 }}
    {{- end }}
    {{- if $.Values.graphdb.import_directory_mount.enabled }}
    - metadata:
        name: graphdb-server-import-dir
      {{- $spec := dict "globalStorageClassName" $.Values.global.storageClass "spec" $.Values.graphdb.import_directory_mount.volumeClaimTemplateSpec }}
      spec: {{ include "renderVolumeClaimTemplateSpec" $spec | nindent 8 }}
    {{- end }}
  {{- end }}
  template:
    metadata:
      labels:
        app: graphdb-node
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/configuration/graphdb-node-configmap.yaml") . | sha256sum }}
    spec:
      setHostnameAsFQDN: true
      terminationGracePeriodSeconds: 120
      volumes:
        {{- if $.Values.graphdb.node.license }}
        - name: graphdb-license
          secret:
            secretName: {{ $.Values.graphdb.node.license }}
        {{- end }}
        {{- if or $configs.settingsConfigMap $.Values.graphdb.security.enabled }}
        - name: graphdb-settings-config
          configMap:
            name: {{ $configs.settingsConfigMap | default "graphdb-settings-configmap" }}
        {{- end }}
        {{- if or $configs.usersConfigMap $.Values.graphdb.security.enabled }}
        - name: graphdb-users-config
          configMap:
            name: {{ $configs.usersConfigMap | default "graphdb-users-configmap" }}
        {{- end }}
        {{- if $configs.propertiesConfigMap }}
        - name: graphdb-properties-config
          configMap:
            name: {{ $configs.propertiesConfigMap }}
        {{- end }}
        {{- if $configs.logbackConfigMap }}
        - name: graphdb-logback-config
          configMap:
            name: {{ $configs.logbackConfigMap }}
        {{- end }}
        {{- with $.Values.graphdb.node.extraVolumes }}
          {{- tpl ( toYaml . ) $ | nindent 8 }}
        {{- end }}
      imagePullSecrets:
        {{- include "combinedImagePullSecrets" $ | nindent 8 }}
      nodeSelector:
        {{- $.Values.graphdb.node.nodeSelector | toYaml | nindent 8 }}
      affinity:
        {{- $.Values.graphdb.node.affinity | toYaml | nindent 8 }}
      tolerations:
        {{- $.Values.graphdb.node.tolerations | toYaml | nindent 8 }}
      topologySpreadConstraints:
        {{- $.Values.graphdb.node.topologySpreadConstraints | toYaml | nindent 8 }}
      securityContext:
        {{- $.Values.graphdb.node.podSecurityContext | toYaml | nindent 8 }}
      containers:
        - name: graphdb-node
          image: {{ include "renderFullImageName" (dict "globalRegistry" $.Values.global.imageRegistry "image" $.Values.images.graphdb) }}
          imagePullPolicy: {{ $.Values.deployment.imagePullPolicy }}
          ports:
            - name: graphdb
              containerPort: 7200
              {{- if gt (int (.Values.graphdb.clusterConfig.nodesCount)) 1 }}
            - name: graphdb-rpc
              containerPort: 7300
              {{- end }}
          envFrom:
            - configMapRef:
                name: graphdb-node-configmap
            {{- with $.Values.graphdb.node.extraEnvFrom }}
              {{- tpl ( toYaml . ) $ | nindent 12 }}
            {{- end }}
          volumeMounts:
            {{- if hasKey $.Values.graphdb.node.persistence "volumeClaimTemplateSpec" }}
            - name: graphdb-node-data-dynamic-pvc
            {{- else }}
            - name: graphdb-node-storage
            {{- end }}
              mountPath: /opt/graphdb/home
            {{- if $.Values.graphdb.import_directory_mount.enabled }}
            - name: graphdb-server-import-dir
              mountPath: /opt/graphdb/home/graphdb-import
            {{- end }}
            {{- with $.Values.graphdb.node.extraVolumeMounts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          resources: {{ $.Values.graphdb.node.resources | toYaml | nindent 12 }}
          securityContext: {{ $.Values.graphdb.node.securityContext | toYaml | nindent 12 }}
          # Allow for GraphDB to start within 10*30 seconds before readiness & liveness probes interfere
          startupProbe: {{ $.Values.graphdb.node.startupProbe | toYaml | nindent 12 }}
          readinessProbe: {{ $.Values.graphdb.node.readinessProbe | toYaml | nindent 12 }}
          livenessProbe: {{ $.Values.graphdb.node.livenessProbe | toYaml | nindent 12 }}
      initContainers:
      {{- if $.Values.graphdb.node.license }}
        # LICENSE PROVISION
        - name: provision-license
          image: {{ include "renderFullImageName" (dict "globalRegistry" $.Values.global.imageRegistry "image" $.Values.images.busybox) }}
          imagePullPolicy: {{ $.Values.deployment.imagePullPolicy }}
          volumeMounts:
            {{- if hasKey $.Values.graphdb.node.persistence "volumeClaimTemplateSpec" }}
            - name: graphdb-node-data-dynamic-pvc
            {{- else }}
            - name: graphdb-node-storage
            {{- end }}
              mountPath: /opt/graphdb/home
            - name: graphdb-license
              mountPath: /tmp/license/
          securityContext: {{ $.Values.graphdb.node.initContainerSecurityContext | toYaml | nindent 12 }}
          command: ['sh', '-c']
          args:
            - |
              mkdir -p /opt/graphdb/home/conf/
              cd /opt/graphdb/home/conf/
              [ -f graphdb.license ] && rm graphdb.license

              mkdir -p /opt/graphdb/home/work/
              cd /opt/graphdb/home/work/
              [ -f graphdb.license ] && rm graphdb.license

              echo 'Provisioning GraphDB node license'
              cp /tmp/license/*.license ./graphdb.license
              echo 'Done'
        {{- end }}
        # PROVISION SETTINGS AND SECURITY
        - name: provision-settings
          image: {{ include "renderFullImageName" (dict "globalRegistry" $.Values.global.imageRegistry "image" $.Values.images.busybox) }}
          imagePullPolicy: {{ $.Values.deployment.imagePullPolicy }}
          volumeMounts:
            {{- if hasKey $.Values.graphdb.node.persistence "volumeClaimTemplateSpec" }}
            - name: graphdb-node-data-dynamic-pvc
            {{- else }}
            - name: graphdb-node-storage
            {{- end }}
              mountPath: /opt/graphdb/home
            {{- if or $configs.settingsConfigMap $.Values.graphdb.security.enabled }}
            - name: graphdb-settings-config
              mountPath: /tmp/graphdb-settings-configmap
            {{- end }}
            {{- if or $configs.usersConfigMap $.Values.graphdb.security.enabled }}
            - name: graphdb-users-config
              mountPath: /tmp/graphdb-users-configmap
            {{- end }}
            {{- if $configs.propertiesConfigMap }}
            - name: graphdb-properties-config
              mountPath: /tmp/graphdb-properties-configmap
            {{- end }}
            {{- if $configs.logbackConfigMap }}
            - name: graphdb-logback-config
              mountPath: /tmp/graphdb-logback-configmap
            {{- end }}
          securityContext: {{ $.Values.graphdb.node.initContainerSecurityContext | toYaml | nindent 12 }}
          command: ['sh', '-c']
          args:
            - |
              set -eu
              if [[ ! -f /opt/graphdb/home/work/workbench/settings.js && ! -f /opt/graphdb/home/data/users.js && -f /tmp/graphdb-users-configmap/users.js ]]; then
                echo "Provisioning users with users.js file..."
                mkdir -p /opt/graphdb/home/data ;
                cp /tmp/graphdb-users-configmap/users.js /opt/graphdb/home/data/users.js
              fi
              if [[ ! -f /opt/graphdb/home/work/workbench/settings.js && ! -f /opt/graphdb/home/data/settings.js && -f /tmp/graphdb-settings-configmap/settings.js ]]; then
                echo "Provisioning settings with settings.js file..."
                mkdir -p /opt/graphdb/home/data ;
                cp /tmp/graphdb-settings-configmap/settings.js /opt/graphdb/home/data/settings.js
              fi
              if [[ -f /tmp/graphdb-properties-configmap/graphdb.properties ]]; then
                echo "Provisioning graphdb properties file..."
                mkdir -p /opt/graphdb/home/conf ;
                cp /tmp/graphdb-properties-configmap/graphdb.properties /opt/graphdb/home/conf/graphdb.properties
              fi
              if [[ -f /tmp/graphdb-logback-configmap/logback.xml ]]; then
                echo "Provisioning logging config file..."
                mkdir -p /opt/graphdb/home/conf ;
                cp /tmp/graphdb-logback-configmap/logback.xml /opt/graphdb/home/conf/logback.xml
              fi
              mkdir -p /opt/graphdb/home/jdbc-driver
              echo 'Done'

---
apiVersion: {{ $.Values.versions.service }}
kind: Service
metadata:
  name: graphdb-node
  labels:
    app: graphdb-node
    {{- include "graphdb.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    app: graphdb-node
  ports:
    - name: graphdb
      port: 7200
      targetPort: 7200
      protocol: TCP
{{- if gt (int $.Values.graphdb.clusterConfig.nodesCount) 1 }}
    - name: rpc
      port: 7300
      targetPort: 7300
      protocol: TCP
{{- end }}
