{{- if .Values.deployment.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "graphdb.fullname" . }}
  labels:
    {{- include "graphdb.labels" . | nindent 4 }}
    {{- with .Values.deployment.ingress.labels }}
      {{- tpl ( toYaml . ) $ | nindent 4 }}
    {{- end }}
  annotations:
    {{- with (mergeOverwrite (deepCopy .Values.annotations) .Values.deployment.ingress.annotations) }}
      {{- tpl ( toYaml . ) $ | nindent 4 }}
    {{- end }}
spec:
  {{- with .Values.deployment.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- if or .Values.deployment.tls.enabled .Values.deployment.ingress.extraTLS }}
  tls:
    {{- if .Values.deployment.tls.enabled }}
    - hosts:
        - {{ coalesce .Values.deployment.ingress.host .Values.deployment.host }}
      secretName: {{ required "TLS secret is required!" .Values.deployment.tls.secretName }}
    {{- end }}
    {{- with .Values.deployment.ingress.extraTLS }}
      {{- tpl ( toYaml . ) $ | nindent 4 }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ coalesce .Values.deployment.ingress.host .Values.deployment.host }}
      http:
        paths:
          - path: {{ coalesce .Values.deployment.ingress.path .Values.graphdb.workbench.subpath }}
            pathType: {{ .Values.deployment.ingress.pathType }}
            backend:
              service:
                {{- if gt (int $.Values.graphdb.clusterConfig.nodesCount) 1 }}
                name: {{ include "graphdb-proxy.fullname" . }}
                port:
                  number: {{ .Values.graphdb.clusterProxy.service.ports.http }}
                {{- else }}
                name: {{ include "graphdb.fullname.service.headless" . }}
                port:
                  number: {{ .Values.graphdb.node.headlessService.ports.http }}
                {{- end }}
    {{- with .Values.deployment.ingress.extraHosts }}
      {{- tpl ( toYaml . ) $ | nindent 4 }}
    {{- end }}
{{- end }}
