{{- if .Values.deployment.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "graphdb.fullname" . }}
  labels:
    {{- include "graphdb.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.deployment.ingress.class }}
    {{- if .Values.deployment.tls.enabled }}
    ingress.kubernetes.io/force-ssl-redirect: "true"
    {{- end }}
    nginx.ingress.kubernetes.io/proxy-body-size: {{ .Values.deployment.ingress.maxRequestSize }}
    nginx.ingress.kubernetes.io/proxy-connect-timeout: {{ .Values.deployment.ingress.timeout.connect | quote }}
    nginx.ingress.kubernetes.io/proxy-read-timeout: {{ .Values.deployment.ingress.timeout.read | quote }}
    nginx.ingress.kubernetes.io/proxy-send-timeout: {{ .Values.deployment.ingress.timeout.send | quote }}
    {{- if eq $.Values.graphdb.workbench.subpath "/" }}
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    {{- else }}
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    {{- end }}
    nginx.ingress.kubernetes.io/x-forwarded-prefix: {{ $.Values.graphdb.workbench.subpath | quote }}
    {{- with (mergeOverwrite (deepCopy .Values.annotations) .Values.deployment.ingress.annotations) }}
      {{- tpl ( toYaml . ) $ | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.deployment.tls.enabled }}
  tls:
    - hosts:
        - {{ include "graphdb.resolveDeploymentHost" . | quote }}
      secretName: {{ required "TLS secret is required!" .Values.deployment.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ include "graphdb.resolveDeploymentHost" . | quote }}
      http:
        paths:
          {{- if eq $.Values.graphdb.workbench.subpath "/" }}
          - path: /(.*)
          {{- else }}
          - path: {{ $.Values.graphdb.workbench.subpath }}(/|$)(.*)
          {{- end }}
            pathType: ImplementationSpecific
            backend:
              service:
              {{- if gt (int $.Values.graphdb.clusterConfig.nodesCount) 1 }}
                name: {{ include "graphdb-proxy.fullname" . }}
              {{- else }}
                name: {{ include "graphdb.fullname.service.headless" . }}
              {{- end }}
                port:
                  number: 7200
{{- end }}
