apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "graphdb.fullname.configmap.utils" . }}
  labels:
    {{- include "graphdb.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade, pre-rollback, post-install, post-upgrade, post-rollback
    "helm.sh/hook-delete-policy": before-hook-creation, hook-succeeded, hook-failed
    "helm.sh/hook-weight": "-10"
    {{- with .Values.annotations }}
      {{- tpl ( toYaml . ) $ | nindent 4 }}
    {{- end }}
data:
  graphdb.sh: |-
    {{- tpl (.Files.Get "files/scripts/graphdb.sh" | trim ) . | nindent 4 }}
  update-cluster.sh: |-
    {{- tpl (.Files.Get "files/scripts/update-cluster.sh" | trim ) . | nindent 4 }}
