apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "graphdb.fullname.job.scale-down-cluster" . }}
  labels:
    {{- include "graphdb.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-upgrade, pre-rollback
    "helm.sh/hook-delete-policy": before-hook-creation, hook-succeeded, hook-failed
    {{- with .Values.annotations }}
      {{- tpl ( toYaml . ) $ | nindent 4 }}
    {{- end }}
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 4
  template:
    spec:
      restartPolicy: Never
      {{- if or .Values.global.imagePullSecrets .Values.deployment.imagePullSecrets }}
      imagePullSecrets:
        {{- include "graphdb.combinedImagePullSecrets" . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- $.Values.graphdb.jobPodSecurityContext | toYaml | nindent 8 }}
      containers:
        - name: scale-down-cluster
          image: {{ include "graphdb.image" . }}
          env:
            - name: GRAPHDB_POD_NAME
              value: {{ include "graphdb.fullname" . }}
            - name: GRAPHDB_SERVICE_NAME
              value: {{ include "graphdb.fullname.service.headless" . }}
            - name: GRAPHDB_PROXY_SERVICE_NAME
              value: {{ include "graphdb-proxy.fullname" . }}
          envFrom:
            - secretRef:
                name: {{ include "graphdb.fullname.secret.provision-user" . }}
          securityContext: {{- $.Values.graphdb.jobSecurityContext | toYaml | nindent 12 }}
          {{- with .Values.graphdb.jobResources }}
          resources: {{ toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: job-temp
              mountPath: /tmp
            - name: graphdb-utils
              mountPath: /tmp/utils
          command: ['bash']
          args:
            - "/tmp/utils/update-cluster.sh"
            - "removeNodes"
            - "{{ .Values.graphdb.clusterConfig.nodesCount }}"
            - "{{ $.Release.Namespace }}"
      volumes:
        - name: job-temp
          emptyDir:
            sizeLimit: 10Mi
        - name: graphdb-utils
          configMap:
            name: {{ include "graphdb.fullname.configmap.utils" . }}
