{{- if .Values.repositories.repositoriesConfigmap }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "graphdb.fullname.job.provision-repositories" . }}
  labels:
    {{- include "graphdb.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install, post-upgrade, post-rollback
    "helm.sh/hook-delete-policy": before-hook-creation, hook-succeeded, hook-failed
    "helm.sh/hook-weight": "4"
    {{- with .Values.annotations }}
      {{- tpl ( toYaml . ) $ | nindent 4 }}
    {{- end }}
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      {{- if or .Values.global.imagePullSecrets .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- include "graphdb.combinedImagePullSecrets" . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- $.Values.jobs.podSecurityContext | toYaml | nindent 8 }}
      containers:
        - name: provision-repositories
          image: {{ include "graphdb.image" . }}
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          env:
            - name: GRAPHDB_POD_NAME
              value: {{ include "graphdb.fullname" . }}
            - name: GRAPHDB_SERVICE_NAME
              value: {{ include "graphdb.fullname.service.headless" . }}
            - name: GRAPHDB_SERVICE_PORT
              value: {{ .Values.headlessService.ports.http | quote }}
          envFrom:
            - secretRef:
                name: {{ include "graphdb.fullname.secret.provision-user" . }}
          securityContext: {{- $.Values.jobs.securityContext | toYaml | nindent 12 }}
          {{- with .Values.jobs.resources }}
          resources: {{ toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: job-temp
              mountPath: /tmp
            - name: graphdb-utils
              mountPath: /tmp/utils
            - name: repositories-config
              mountPath: /tmp/repositories-config
          command: ['bash']
          args:
            - "/tmp/utils/graphdb.sh"
            - "createRepositoryFromFile"
            - "{{ .Values.replicas }}"
            - "/tmp/repositories-config"
      volumes:
        - name: job-temp
          emptyDir:
            sizeLimit: 10Mi
        - name: repositories-config
          configMap:
            name: {{ .Values.repositories.repositoriesConfigmap }}
        - name: graphdb-utils
          configMap:
            name: {{ include "graphdb.fullname.configmap.utils" . }}
{{- end }}
