{{- if and .Values.cluster.jobs.createCluster.enabled (gt (int .Values.replicas) 1) }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "graphdb.fullname.job.create-cluster" . }}
  namespace: {{ include "graphdb.namespace" . }}
  labels:
    {{- include "graphdb.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install, post-upgrade, post-rollback
    "helm.sh/hook-delete-policy": before-hook-creation, hook-succeeded, hook-failed
    "helm.sh/hook-weight": "-1"
    {{- with .Values.annotations }}
      {{- tpl ( toYaml . ) $ | nindent 4 }}
    {{- end }}
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 9
  template:
    spec:
      restartPolicy: Never
      {{- if or .Values.global.imagePullSecrets .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- include "graphdb.combinedImagePullSecrets" . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- .Values.jobs.podSecurityContext | toYaml | nindent 8 }}
      volumes:
        - name: job-temp
          emptyDir:
            sizeLimit: 10Mi
        - name: cluster-config
          configMap:
            name: {{ ( tpl .Values.cluster.existingConfig . ) | default ( include "graphdb.fullname.configmap.cluster" . ) }}
        - name: graphdb-utils
          configMap:
            name: {{ include "graphdb.fullname.configmap.utils" . }}
      containers:
        - name: create-graphdb-cluster
          image: {{ include "graphdb.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: GRAPHDB_POD_NAME
              value: {{ include "graphdb.fullname" . }}
            - name: GRAPHDB_SERVICE_NAME
              value: {{ include "graphdb.fullname.service.headless" . }}
            - name: GRAPHDB_SERVICE_PORT
              value: {{ .Values.headlessService.ports.http | quote }}
          envFrom:
            - secretRef:
                name: {{ include "graphdb.fullname.secret.provision-user" . }}
          securityContext: {{- .Values.jobs.securityContext | toYaml | nindent 12 }}
          {{- with .Values.jobs.resources }}
          resources: {{ toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: job-temp
              mountPath: /tmp
            - name: graphdb-utils
              mountPath: /tmp/utils
            - name: cluster-config
              mountPath: /tmp/cluster-config/cluster-config.json
              subPath: {{ .Values.cluster.existingConfigmapKey }}
          command: ['bash']
          args:
            - "/tmp/utils/graphdb.sh"
            - createCluster
            - "{{ .Values.replicas }}"
            - "/tmp/cluster-config/cluster-config.json"
            - "{{ .Values.cluster.clusterCreationTimeout }}"
{{- end }}
