{{- if hasKey .Values.graphdb.backupRestore "trigger_backup"}}
apiVersion: batch/v1
kind: Job
metadata:
  name: run-manual-backup
spec:
  ttlSecondsAfterFinished: 60
  template:
    spec:
      containers:
        - name: run-script-manual-backup
          image: {{ .Values.images.graphdb }}
          volumeMounts:
            - name: graphdb-utils
              mountPath: /tmp/utils
          command: ['bash',
                    '-c']
          args:
            - |
              cp /tmp/utils/runManualBackup.sh /tmp/utils/backup.sh /usr/local/bin/;
              chmod +x /usr/local/bin/runManualBackup.sh;
              chmod +x /usr/local/bin/backup.sh;
              {{- range .Values.graphdb.backupRestore.repositories }}
              /usr/local/bin/runManualBackup.sh "{{ $.Values.graphdb.backupRestore.trigger_backup }}" "{{ . }}" {{ $.Values.graphdb.topology | quote }}
              {{- end }}
              >> /proc/1/fd/1
      restartPolicy: OnFailure
      volumes:
        - name: graphdb-utils
          configMap:
            name: graphdb-utils-configmap
{{- end }}
