{{- if gt (int .Values.graphdb.clusterConfig.nodesCount) 1 }}
apiVersion: {{ $.Values.versions.job }}
kind: Job
metadata:
  name: patch-cluster-job
  labels:
    {{- include "graphdb.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-upgrade, post-rollback
    "helm.sh/hook-delete-policy": before-hook-creation, hook-succeeded, hook-failed
    "helm.sh/hook-weight": "2"
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      imagePullSecrets:
        {{- include "combinedImagePullSecrets" $ | nindent 8 }}
      securityContext:
        {{- $.Values.graphdb.jobPodSecurityContext | toYaml | nindent 8 }}
      containers:
        - name: patch-cluster
          image: {{ include "renderFullImageName" (dict "globalRegistry" $.Values.global.imageRegistry "image" $.Values.images.graphdb) }}
          envFrom:
            - secretRef:
                name: graphdb-provision-user
          securityContext: {{- $.Values.graphdb.jobSecurityContext | toYaml | nindent 12 }}
          volumeMounts:
            - name: graphdb-utils
              mountPath: /tmp/utils
            - name: cluster-config
              mountPath: /tmp/cluster-config
          command: ['sh','-c']
          args:
            - |
              cp /tmp/cluster-config/cluster-config.json /usr/local/bin/cluster-config.json
              cp /tmp/utils/update-cluster.sh /usr/local/bin/update-cluster.sh; chmod +x /usr/local/bin/update-cluster.sh
              /usr/local/bin/update-cluster.sh patchCluster "/usr/local/bin/cluster-config.json" >> /proc/1/fd/1
      restartPolicy: Never
      volumes:
        - name: cluster-config
          configMap:
            name: graphdb-cluster-config-configmap
        - name: graphdb-utils
          configMap:
            name: graphdb-utils-configmap
  backoffLimit: 4
{{- end }}
