{{- if gt (int .Values.graphdb.clusterConfig.nodesCount) 1 }}
apiVersion: batch/v1
kind: Job
metadata:
  name: patch-cluster-job
  labels:
    {{- include "graphdb.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-upgrade, post-rollback
    "helm.sh/hook-delete-policy": before-hook-creation, hook-succeeded, hook-failed
    "helm.sh/hook-weight": "2"
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 4
  template:
    spec:
      restartPolicy: Never
      imagePullSecrets:
        {{- include "graphdb.combinedImagePullSecrets" $ | nindent 8 }}
      securityContext:
        {{- $.Values.graphdb.jobPodSecurityContext | toYaml | nindent 8 }}
      containers:
        - name: patch-cluster
          image: {{ include "graphdb.renderFullImageName" (dict "globalRegistry" $.Values.global.imageRegistry "image" $.Values.images.graphdb) }}
          envFrom:
            - secretRef:
                name: graphdb-provision-user
          securityContext: {{- $.Values.graphdb.jobSecurityContext | toYaml | nindent 12 }}
          {{- with .Values.graphdb.jobResources }}
          resources: {{ toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: job-temp
              mountPath: /tmp
            - name: graphdb-utils
              mountPath: /tmp/utils
            - name: cluster-config
              mountPath: /tmp/cluster-config
          command: ['bash']
          args:
            - "/tmp/utils/update-cluster.sh"
            - "patchCluster"
            - "/tmp/cluster-config/cluster-config.json"
      volumes:
        - name: job-temp
          emptyDir:
            sizeLimit: 10Mi
        - name: cluster-config
          configMap:
            name: graphdb-cluster-config-configmap
        - name: graphdb-utils
          configMap:
            name: graphdb-utils-configmap
{{- end }}
