{{- $configs := (.Values.graphdb.configs | default dict) }}
{{- if $configs.provisionRepositoriesConfigMap }}
apiVersion: {{ $.Values.versions.job }}
kind: Job
metadata:
  name: provision-repositories-job
  labels:
    {{- include "graphdb.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install, post-upgrade, post-rollback
    "helm.sh/hook-delete-policy": before-hook-creation, hook-succeeded, hook-failed
    "helm.sh/hook-weight": "4"
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      imagePullSecrets:
        {{- include "combinedImagePullSecrets" $ | nindent 8 }}
      securityContext:
        {{- $.Values.graphdb.jobPodSecurityContext | toYaml | nindent 8 }}
      containers:
        - name: provision-repositories
          image: {{ include "renderFullImageName" (dict "globalRegistry" $.Values.global.imageRegistry "image" $.Values.images.graphdb) }}
          envFrom:
            - secretRef:
                name: graphdb-provision-user
          securityContext: {{- $.Values.graphdb.jobSecurityContext | toYaml | nindent 12 }}
          volumeMounts:
            - name: job-temp
              mountPath: /tmp
            - name: graphdb-utils
              mountPath: /tmp/utils
            - name: repositories-config
              mountPath: /tmp/repositories-config
          command: ['bash']
          args:
            - "/tmp/utils/graphdb.sh"
            - "createRepositoryFromFile"
            - "{{ .Values.graphdb.clusterConfig.nodesCount }}"
            - "/tmp/repositories-config"
      volumes:
        - name: job-temp
          emptyDir:
            sizeLimit: 10Mi
        - name: repositories-config
          configMap:
            name: {{ .Values.graphdb.configs.provisionRepositoriesConfigMap }}
        - name: graphdb-utils
          configMap:
            name: graphdb-utils-configmap
{{- end }}
