apiVersion: batch/v1
kind: Job
metadata:
  name: scale-down-cluster-job
  labels:
    {{- include "graphdb.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-upgrade, pre-rollback
    "helm.sh/hook-delete-policy": before-hook-creation, hook-succeeded, hook-failed
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 4
  template:
    spec:
      restartPolicy: Never
      imagePullSecrets:
        {{- include "graphdb.combinedImagePullSecrets" $ | nindent 8 }}
      securityContext:
        {{- $.Values.graphdb.jobPodSecurityContext | toYaml | nindent 8 }}
      containers:
        - name: scale-down-cluster
          image: {{ include "graphdb.renderFullImageName" (dict "globalRegistry" $.Values.global.imageRegistry "image" $.Values.images.graphdb) }}
          envFrom:
            - secretRef:
                name: graphdb-provision-user
          securityContext: {{- $.Values.graphdb.jobSecurityContext | toYaml | nindent 12 }}
          {{- with .Values.graphdb.jobResources }}
          resources: {{ toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: job-temp
              mountPath: /tmp
            - name: graphdb-utils
              mountPath: /tmp/utils
          command: ['bash']
          args:
            - "/tmp/utils/update-cluster.sh"
            - "removeNodes"
            - "{{ .Values.graphdb.clusterConfig.nodesCount }}"
            - "{{ $.Release.Namespace }}"
      volumes:
        - name: job-temp
          emptyDir:
            sizeLimit: 10Mi
        - name: graphdb-utils
          configMap:
            name: graphdb-utils-configmap
