{{- if not .Values.security.provisioner.existingSecret }}
# Secret used from the jobs to authenticate to running GraphDB instances
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "graphdb.fullname.secret.provisioning-user" . }}
  namespace: {{ include "graphdb.namespace" . }}
  labels:
    {{- include "graphdb.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade, pre-rollback, post-install, post-upgrade, post-rollback
    "helm.sh/hook-delete-policy": before-hook-creation, hook-succeeded, hook-failed
    "helm.sh/hook-weight": "-9"
    {{- with .Values.annotations }}
    annotations:
      {{- tpl (toYaml .) $ | nindent 4 }}
    {{- end }}
type: Opaque
data:
  {{ .Values.security.provisioner.tokenKey }}: {{ printf "%s:%s" .Values.security.provisioner.username .Values.security.provisioner.password | b64enc | b64enc | quote }}
{{- end }}
