{{- if not .Values.security.provisioner.existingSecret }}
# Secret used from the jobs to authenticate to running GraphDB instances
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "graphdb.fullname.secret.provisioning-user" . }}
  namespace: {{ include "graphdb.namespace" . }}
  labels:
    {{- include "graphdb.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install, post-upgrade, post-rollback
    {{- if .Values.backup.enabled }}
    "helm.sh/hook-delete-policy": before-hook-creation
    {{- else }}
    "helm.sh/hook-delete-policy": before-hook-creation, hook-succeeded, hook-failed
    {{- end }}
    "helm.sh/hook-weight": "-9"
    {{- with .Values.annotations }}
      {{- tpl (toYaml .) $ | nindent 4 }}
    {{- end }}
type: Opaque
data:
  {{ .Values.security.provisioner.tokenKey }}: {{ printf "%s:%s" .Values.security.provisioner.username .Values.security.provisioner.password | b64enc | b64enc | quote }}
{{- end }}
