{{- if and .Values.backup.enabled (not .Values.backup.optionsSecret.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "graphdb.fullname.secret.backup-options" . }}
  namespace: {{ include "graphdb.namespace" . }}
  labels:
    {{- include "graphdb.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{ .Values.backup.optionsSecret.secretKey }}: |
    {{- include "graphdb.backup.options.json" . | nindent 4 }}
{{- end }}
