{{- if and .Values.backup.enabled (not .Values.backup.optionsSecret.existingSecret) }}
{{- $options := dict }}
{{- if eq .Values.backup.type "cloud" -}}
  {{- $options = set $options "bucketUri" (required "backup.cloud.bucketUri is required" .Values.backup.cloud.bucketUri) -}}
{{- end -}}
{{- $options = merge (default dict .Values.backup.options) $options -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "graphdb.fullname.secret.backup-options" . }}
  namespace: {{ include "graphdb.namespace" . }}
  labels:
    {{- include "graphdb.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{ .Values.backup.optionsSecret.secretKey }}: |
    {{- $options | toPrettyJson | nindent 4 }}
{{- end }}
