{{- if gt (int .Values.replicas) 1 }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "graphdb-proxy.fullname.configmap.properties" . }}
  namespace: {{ include "graphdb.namespace" . }}
  labels:
    {{- include "graphdb-proxy.labels" . | nindent 4 }}
  {{- with (mergeOverwrite (deepCopy .Values.annotations) .Values.proxy.annotations) }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
data:
  graphdb.properties: |-
    ##### GraphDB configurations #####
    # See https://graphdb.ontotext.com/documentation/ for supported properties
    graphdb.connector.port={{ .Values.proxy.containerPorts.http }}
    graphdb.proxy.hosts={{ include "graphdb-proxy.cluster.nodes" . }}
    {{- if .Values.proxy.configuration.properties }}
    ##### Overrides from values.yaml #####
    {{- range $key, $val := .Values.proxy.configuration.properties -}}
    {{- if ne $val nil }}
    {{ $key }}={{ tpl ($val | toString) $ | quote }}
    {{- end }}
    {{- end -}}
    {{- end -}}
    {{- with .Values.cluster.tls }}
    graphdb.raft.security.mode={{ .mode }}
    {{- if .privateKey.secretName }}
    graphdb.raft.security.certificateKeyFile=/etc/graphdb/private-key.pem
    {{- end }}
    {{- if .certificate.secretName }}
    graphdb.raft.security.certificateFile=/etc/graphdb/certificate.pem
    {{- end }}
    {{- if .certificateChain.secretName }}
    graphdb.raft.security.certificateChainFile=/etc/graphdb/certificate-chain.pem
    {{- end }}
    {{- if .keystore.secretName }}
    graphdb.raft.security.keystoreFile=/etc/graphdb/keystore.jks
    graphdb.raft.security.keyAlias={{ .keystore.keyAlias }}
    {{- if .keystore.keystoreProvider }}
    graphdb.raft.security.keystoreProvider={{ .keystore.keystoreProvider }}
    {{- end }}
    {{- if .keystore.keystoreType }}
    graphdb.raft.security.keystoreType={{ .keystore.keystoreType }}
    {{- end }}
    {{- end }}
    {{- if .truststore.secretName }}
    graphdb.raft.security.truststoreFile=/etc/graphdb/truststore.jks
    {{- if .truststore.truststoreProvider }}
    graphdb.raft.security.truststoreProvider={{ .truststore.truststoreProvider }}
    {{- end }}
    {{- if .truststore.truststoreType }}
    graphdb.raft.security.truststoreType={{ .truststore.truststoreType }}
    {{- end }}
    {{- end }}
    {{- if .rootCerts.secretName }}
    graphdb.raft.security.rootCerts=/etc/graphdb/root-certs.pem
    {{- end }}
    {{- if .certificateRevocationList.secretName }}
    graphdb.raft.security.certificateRevocationListFile=/etc/graphdb/certificate-revocation-list.pem
    {{- end }}
    {{- end }}
{{- end }}
