{{- if gt (int $.Values.graphdb.clusterConfig.nodesCount) 1 }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: graphdb-cluster-proxy-configmap
  labels:
    {{- include "graphdb.labels" . | nindent 4 }}
data:
  # >- means replace new line with space and no new lines at the end
  GDB_JAVA_OPTS: >-
    -Dgraphdb.vhosts={{ $.Values.deployment.protocol }}://{{ include "graphdb.resolveDeploymentHost" $ }}{{ $.Values.graphdb.workbench.subpath }}
    -Dgraphdb.external-url={{ $.Values.deployment.protocol }}://{{ include "graphdb.resolveDeploymentHost" $ }}{{ $.Values.graphdb.workbench.subpath }}
    -Dgraphdb.auth.token.secret={{ $.Values.graphdb.clusterConfig.clusterSecret | quote }}
    -Dgraphdb.home=/opt/graphdb/home
    {{ $.Values.graphdb.clusterProxy.java_args }}
{{- end }}
