{{- if gt (int .Values.replicas) 1 }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "graphdb-proxy.fullname.configmap.properties" . }}
  labels:
    {{- include "graphdb-proxy.labels" . | nindent 4 }}
  {{- with (mergeOverwrite (deepCopy .Values.annotations) .Values.proxy.annotations) }}
  annotations:
    {{- tpl ( toYaml . ) $ | nindent 4 }}
  {{- end }}
data:
  graphdb.properties: |-
    {{- tpl ( .Files.Get "files/config/proxy/graphdb.properties" ) . | nindent 4 }}
{{- end }}
