{{- if gt (int $.Values.graphdb.clusterConfig.nodesCount) 1 }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "graphdb-proxy.fullname" . }}
  labels:
    {{- include "graphdb-proxy.labels" . | nindent 4 }}
  {{- with .Values.proxy.annotations }}
  annotations:
    {{- tpl ( toYaml . ) $ | nindent 4 }}
  {{- end }}
data:
  # >- means replace new line with space and no new lines at the end
  GDB_JAVA_OPTS: >-
    -Dgraphdb.auth.token.secret={{ $.Values.graphdb.clusterConfig.clusterSecret | quote }}
    -Dgraphdb.home=/opt/graphdb/home
    {{ $.Values.graphdb.clusterProxy.java_args }}
{{- end }}
