{{- if gt (int .Values.replicas) 1 }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "graphdb-proxy.fullname.configmap.environment" . }}
  namespace: {{ include "graphdb.namespace" . }}
  labels:
    {{- include "graphdb-proxy.labels" . | nindent 4 }}
  {{- with (mergeOverwrite (deepCopy .Values.annotations) .Values.proxy.annotations) }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
data:
  GDB_JAVA_OPTS: >-
    -Dgraphdb.home=/opt/graphdb/home
    -Dhttp.socket.keepalive=true
    {{ .Values.proxy.configuration.defaultJavaArguments }}
    {{ .Values.proxy.configuration.javaArguments }}
{{- end }}
