{{- if gt (int .Values.replicas) 1 }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "graphdb-proxy.fullname.secret.properties" . }}
  namespace: {{ include "graphdb.namespace" . }}
  labels:
    {{- include "graphdb-proxy.labels" . | nindent 4 }}
  {{- with (mergeOverwrite (deepCopy .Values.annotations) .Values.proxy.annotations) }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  graphdb-secrets.properties: |-
    ##### GraphDB sensitive configurations #####
    {{- if not .Values.cluster.token.existingSecret }}
    graphdb.auth.token.secret={{ .Values.cluster.token.secret | quote }}
    {{- end }}
    {{- if .Values.proxy.configuration.secretProperties }}
    ##### Secrets overrides from values.yaml #####
    {{- range $key, $val := .Values.proxy.configuration.secretProperties -}}
    {{- if ne $val nil }}
    {{ $key }}={{ tpl ($val | toString) $ }}
    {{- end }}
    {{- end -}}
    {{- end -}}
{{- end }}
