{{- if and .Values.proxy.service.enabled (gt (int .Values.replicas) 1) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "graphdb-proxy.fullname" . }}
  namespace: {{ include "graphdb.namespace" . }}
  labels:
    {{- include "graphdb-proxy.labels" . | nindent 4 }}
    {{- with .Values.proxy.service.labels }}
      {{- tpl ( toYaml . ) $ | nindent 4 }}
    {{- end }}
  {{- with (mergeOverwrite (deepCopy .Values.annotations) .Values.proxy.annotations .Values.proxy.service.annotations) }}
  annotations:
    {{- tpl ( toYaml . ) $ | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.proxy.service.type }}
  selector:
    {{- include "graphdb-proxy.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.proxy.service.ports.http }}
      targetPort: http
      protocol: TCP
      {{- if .Values.proxy.service.nodePort }}
      nodePort: {{ .Values.proxy.service.nodePort }}
      {{- end }}
{{- end }}
