{{- if gt (int $.Values.graphdb.clusterConfig.nodesCount) 1 }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "graphdb-proxy.fullname" . }}
  labels:
    {{- include "graphdb-proxy.labels" . | nindent 4 }}
    {{- with .Values.graphdb.clusterProxy.service.labels }}
      {{- tpl ( toYaml . ) $ | nindent 4 }}
    {{- end }}
  {{- with (mergeOverwrite (deepCopy .Values.proxy.annotations) .Values.graphdb.clusterProxy.service.annotations) }}
  annotations:
    {{- tpl ( toYaml . ) $ | nindent 4 }}
  {{- end }}
spec:
  type: {{ $.Values.graphdb.clusterProxy.serviceType }}
  selector:
    {{- include "graphdb-proxy.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.graphdb.clusterProxy.service.ports.http }}
      targetPort: http
      protocol: TCP
      {{- if .Values.graphdb.clusterProxy.service.nodePort }}
      nodePort: {{ .Values.graphdb.clusterProxy.service.nodePort }}
      {{- end }}
{{- end }}
