{{- if gt (int $.Values.graphdb.clusterConfig.nodesCount) 1 }}
apiVersion: v1
kind: Service
metadata:
  name: graphdb-cluster-proxy
  labels:
    app: graphdb-cluster-proxy
    {{- include "graphdb.labels" . | nindent 4 }}
  {{- with .Values.graphdb.clusterProxy.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ $.Values.graphdb.clusterProxy.serviceType }}
  selector:
    app: graphdb-cluster-proxy
  ports:
    - name: gdb-proxy-port
      port: 7200
      targetPort: 7200
      protocol: TCP
{{- end }}
