{{- if gt (int $.Values.graphdb.clusterConfig.nodesCount) 1 }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "graphdb-proxy.fullname.service.headless" . }}
  labels:
    {{- include "graphdb-proxy.labels" . | nindent 4 }}
  {{- with (mergeOverwrite (deepCopy .Values.proxy.annotations) .Values.graphdb.clusterProxy.headlessService.annotations) }}
  annotations:
    {{- tpl ( toYaml . ) $ | nindent 4 }}
  {{- end }}
spec:
  clusterIP: None
  selector:
    {{- include "graphdb-proxy.selectorLabels" . | nindent 4 }}
  ports:
    - name: gdb-proxy-rpc
      port: 7300
      targetPort: 7300
      protocol: TCP
{{- end }}
