{{- if gt (int $.Values.graphdb.clusterConfig.nodesCount) 1 }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "graphdb-proxy.fullname" . }}
  labels:
    {{- include "graphdb-proxy.labels" . | nindent 4 }}
  {{- with (mergeOverwrite (deepCopy .Values.proxy.annotations) .Values.graphdb.clusterProxy.service.annotations) }}
  annotations:
    {{- tpl ( toYaml . ) $ | nindent 4 }}
  {{- end }}
spec:
  type: {{ $.Values.graphdb.clusterProxy.serviceType }}
  selector:
    {{- include "graphdb-proxy.selectorLabels" . | nindent 4 }}
  ports:
    - name: gdb-proxy-port
      port: 7200
      targetPort: 7200
      protocol: TCP
{{- end }}
