{{- if gt (int .Values.replicas) 1 }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "graphdb-proxy.fullname" . }}
  namespace: {{ include "graphdb.namespace" . }}
  labels:
    {{- include "graphdb-proxy.labels" . | nindent 4 }}
  {{- with (mergeOverwrite (deepCopy .Values.annotations) .Values.proxy.annotations) }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.proxy.replicas }}
  serviceName: {{ include "graphdb-proxy.fullname.service.headless" . }}
  podManagementPolicy: Parallel
  revisionHistoryLimit: {{ .Values.proxy.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "graphdb-proxy.selectorLabels" . | nindent 6 }}
  {{- if .Values.proxy.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: graphdb-storage
      spec:
        {{- toYaml .Values.proxy.persistence.volumeClaimTemplateSpec | nindent 8 }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "graphdb-proxy.selectorLabels" . | nindent 8 }}
        {{- with .Values.proxy.podLabels }}
          {{- tpl (toYaml .) $ | nindent 8 }}
        {{- end }}
      annotations:
        checksum/configmap: {{ include (print .Template.BasePath "/proxy/configmap.yaml") . | sha256sum }}
        checksum/configmap-properties: {{ include (print .Template.BasePath "/proxy/configmap-properties.yaml") . | sha256sum }}
        checksum/secret-properties: {{ include (print .Template.BasePath "/proxy/secret-properties.yaml") . | sha256sum }}
        {{- with .Values.proxy.podAnnotations }}
          {{- tpl (toYaml .) $ | nindent 8 }}
        {{- end }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.proxy.terminationGracePeriodSeconds }}
      volumes:
        - name: graphdb-properties
          configMap:
            name: {{ include "graphdb-proxy.fullname.configmap.properties" . }}
        - name: graphdb-secret-properties
          secret:
            secretName: {{ include "graphdb-proxy.fullname.secret.properties" . }}
        {{- if .Values.proxy.extraConfiguration.properties.existingConfigmap }}
        - name: graphdb-extra-properties
          configMap:
            name: {{ tpl .Values.proxy.extraConfiguration.properties.existingConfigmap . }}
        {{- end }}
        {{- if .Values.proxy.extraConfiguration.properties.existingSecret }}
        - name: graphdb-extra-secret-properties
          secret:
            secretName: {{ tpl .Values.proxy.extraConfiguration.properties.existingSecret . }}
        {{- end }}
      {{- if .Values.proxy.logging.logback.existingConfigmap }}
        - name: graphdb-logback-config
          configMap:
            name: {{ tpl .Values.proxy.logging.logback.existingConfigmap . }}
      {{- end }}
      {{- with .Values.proxy.extraVolumes }}
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- with .Values.proxy.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.proxy.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.proxy.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.proxy.topologySpreadConstraints }}
      topologySpreadConstraints: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.proxy.podSecurityContext }}
      securityContext: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if or .Values.global.imagePullSecrets .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- include "graphdb.combinedImagePullSecrets" . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "graphdb-proxy.chartName" . }}
          image: {{ include "graphdb.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.proxy.command }}
          command: {{ toYaml .Values.proxy.command | nindent 12 }}
          {{- else }}
          command: ["/opt/graphdb/dist/bin/cluster-proxy"]
          {{- end }}
          {{- with .Values.proxy.args }}
          args: {{ toYaml . | nindent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "graphdb-proxy.fullname" . }}
            {{- with .Values.proxy.extraEnvFrom }}
              {{- tpl (toYaml .) $ | nindent 12 }}
            {{- end }}
          {{- with .Values.proxy.extraEnv }}
          env: {{- tpl (toYaml .) $ | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.proxy.containerPorts.http }}
            - name: rpc
              containerPort: {{ .Values.proxy.containerPorts.rpc }}
            {{- with .Values.proxy.extraContainerPorts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          volumeMounts:
            {{- if .Values.proxy.persistence.enabled }}
            - name: graphdb-storage
              mountPath: /opt/graphdb/home
            {{- end }}
            {{- if .Values.proxy.logging.logback.existingConfigmap }}
            - name: graphdb-logback-config
              mountPath: /opt/graphdb/home/conf/logback.xml
              subPath: {{ .Values.proxy.logging.logback.configmapKey }}
            {{- end }}
            {{- with .Values.proxy.extraVolumeMounts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.proxy.resources }}
          resources: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.proxy.securityContext }}
          securityContext: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.proxy.startupProbe }}
          startupProbe: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.proxy.readinessProbe }}
          readinessProbe: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.proxy.livenessProbe }}
          livenessProbe: {{- toYaml . | nindent 12 }}
          {{- end }}
      initContainers:
        - name: {{ include "graphdb-proxy.chartName" . }}-provision-settings
          image: {{ include "graphdb.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: GRAPHDB_PUBLIC_URL
              value: {{ .Values.configuration.externalUrl }}
            - name: GRAPHDB_PROXY_HTTP_PORT
              value: {{ .Values.proxy.containerPorts.http | quote }}
            - name: GRAPHDB_PROXY_RPC_PORT
              value: {{ .Values.proxy.containerPorts.rpc | quote }}
            {{- if .Values.cluster.existingClusterSecret }}
            - name: GRAPHDB_CLUSTER_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.cluster.existingClusterSecret }}
                  key: {{ .Values.cluster.existingClusterSecretKey }}
            {{- end }}
          {{- with .Values.initContainerSecurityContext }}
          securityContext: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.initContainerResources }}
          resources: {{ toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- if .Values.proxy.persistence.enabled }}
            - name: graphdb-storage
              mountPath: /opt/graphdb/home
            {{- end }}
            - name: graphdb-properties
              mountPath: /tmp/graphdb.properties
              subPath: graphdb.properties
            - name: graphdb-secret-properties
              mountPath: /tmp/graphdb/graphdb-secrets.properties
              subPath: graphdb-secrets.properties
            {{- if .Values.proxy.extraConfiguration.properties.existingConfigmap }}
            - name: graphdb-extra-properties
              mountPath: /tmp/graphdb/graphdb-extra.properties
              subPath: {{ .Values.proxy.extraConfiguration.properties.configmapKey }}
            {{- end }}
            {{- if .Values.proxy.extraConfiguration.properties.existingSecret }}
            - name: graphdb-extra-secret-properties
              mountPath: /tmp/graphdb/graphdb-extra-secret.properties
              subPath: {{ .Values.proxy.extraConfiguration.properties.secretKey }}
            {{- end }}
          command: [ 'sh', '-c' ]
          args:
            - |
              set -eu
              set +x
              mkdir -p /opt/graphdb/home/conf/

              echo 'Configuring graphdb.properties'
              echo "" > /opt/graphdb/home/conf/graphdb.properties

              echo 'Configuring GraphDB cluster proxy hostnames'
              cat << EOF >> /opt/graphdb/home/conf/graphdb.properties
              ##### Configurations from initContainer #####
              graphdb.hostname=$(hostname --fqdn)
              graphdb.rpc.address=$(hostname --fqdn):${GRAPHDB_PROXY_RPC_PORT}
              graphdb.vhosts=$(hostname --fqdn):${GRAPHDB_PROXY_HTTP_PORT}, ${GRAPHDB_PUBLIC_URL}
              graphdb.external-url=${GRAPHDB_PUBLIC_URL}
              EOF
              echo "" >> /opt/graphdb/home/conf/graphdb.properties

              cat /tmp/graphdb.properties >> /opt/graphdb/home/conf/graphdb.properties
              echo "" >> /opt/graphdb/home/conf/graphdb.properties

              cat /tmp/graphdb/graphdb-secrets.properties >> /opt/graphdb/home/conf/graphdb.properties
              echo "" >> /opt/graphdb/home/conf/graphdb.properties

              if [[ -n ${GRAPHDB_CLUSTER_SECRET:-""} ]]; then
                echo "##### Override from existing cluster secret #####" >> /opt/graphdb/home/conf/graphdb.properties
                (echo "graphdb.auth.token.secret=${GRAPHDB_CLUSTER_SECRET}" >> /opt/graphdb/home/conf/graphdb.properties) >/dev/null 2>&1
                echo "" >> /opt/graphdb/home/conf/graphdb.properties
              fi

              if [[ -f /tmp/graphdb/graphdb-extra.properties ]]; then
                echo "##### Overrides from extra properties configmap #####" >> /opt/graphdb/home/conf/graphdb.properties
                cat /tmp/graphdb/graphdb-extra.properties >> /opt/graphdb/home/conf/graphdb.properties
                echo "" >> /opt/graphdb/home/conf/graphdb.properties
              fi

              if [[ -f /tmp/graphdb/graphdb-extra-secret.properties ]]; then
                echo "##### Overrides from extra secret properties #####" >> /opt/graphdb/home/conf/graphdb.properties
                cat /tmp/graphdb/graphdb-extra-secret.properties >> /opt/graphdb/home/conf/graphdb.properties
                echo "" >> /opt/graphdb/home/conf/graphdb.properties
              fi

              echo 'Done'
        {{- with .Values.proxy.extraInitContainers }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
{{- end }}
