{{- if gt (int $.Values.graphdb.clusterConfig.nodesCount) 1 }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "graphdb-proxy.fullname" . }}
  labels:
    {{- include "graphdb-proxy.labels" . | nindent 4 }}
  {{- with .Values.proxy.annotations }}
  annotations:
    {{- tpl ( toYaml . ) $ | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ $.Values.graphdb.clusterProxy.replicas }}
  serviceName: {{ include "graphdb-proxy.fullname.service.headless" . }}
  podManagementPolicy: Parallel
  revisionHistoryLimit: {{ .Values.graphdb.clusterProxy.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "graphdb-proxy.selectorLabels" . | nindent 6 }}
  {{- if .Values.graphdb.clusterProxy.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: graphdb-storage
      spec:
        {{- toYaml .Values.graphdb.clusterProxy.persistence.volumeClaimTemplateSpec | nindent 8 }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "graphdb-proxy.selectorLabels" . | nindent 8 }}
        {{- with .Values.graphdb.clusterProxy.podLabels }}
          {{- tpl ( toYaml . ) $ | nindent 8 }}
        {{- end }}
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/proxy/configmap.yaml") . | sha256sum }}
        {{- with .Values.graphdb.clusterProxy.podAnnotations }}
          {{- tpl ( toYaml . ) $ | nindent 8 }}
        {{- end }}
    spec:
      setHostnameAsFQDN: false
      terminationGracePeriodSeconds: {{ .Values.graphdb.clusterProxy.terminationGracePeriodSeconds }}
      volumes:
        - name: graphdb-properties
          configMap:
            name: {{ include "graphdb-proxy.fullname.configmap.properties" . }}
      {{- with $.Values.graphdb.clusterProxy.extraVolumes }}
        {{- tpl ( toYaml . ) $ | nindent 8 }}
      {{- end }}
      {{- with .Values.graphdb.clusterProxy.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.graphdb.clusterProxy.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.graphdb.clusterProxy.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.graphdb.clusterProxy.topologySpreadConstraints }}
      topologySpreadConstraints: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.graphdb.clusterProxy.podSecurityContext }}
      securityContext: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if or .Values.global.imagePullSecrets .Values.deployment.imagePullSecrets }}
      imagePullSecrets:
        {{- include "graphdb.combinedImagePullSecrets" . | nindent 8 }}
      {{- end }}
      {{- with .Values.graphdb.clusterProxy.extraInitContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "graphdb-proxy.chartName" . }}
          image: {{ include "graphdb.image" . }}
          imagePullPolicy: {{ $.Values.deployment.imagePullPolicy }}
          command: ["/opt/graphdb/dist/bin/cluster-proxy"]
          envFrom:
            - configMapRef:
                name: {{ include "graphdb-proxy.fullname" . }}
            {{- with $.Values.graphdb.clusterProxy.extraEnvFrom }}
              {{- tpl ( toYaml . ) $ | nindent 12 }}
            {{- end }}
          {{- with .Values.graphdb.clusterProxy.extraEnv }}
          env: {{- tpl ( toYaml . ) $ | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.proxy.containerPorts.http }}
            - name: rpc
              containerPort: {{ .Values.proxy.containerPorts.rpc }}
            {{- with .Values.proxy.extraContainerPorts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          volumeMounts:
            {{- if $.Values.graphdb.clusterProxy.persistence.enabled }}
            - name: graphdb-storage
              mountPath: /opt/graphdb/home
            {{- end }}
            {{- with $.Values.graphdb.clusterProxy.extraVolumeMounts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.graphdb.clusterProxy.resources }}
          resources: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.graphdb.clusterProxy.securityContext }}
          securityContext: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.graphdb.clusterProxy.startupProbe }}
          startupProbe: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.graphdb.clusterProxy.readinessProbe }}
          readinessProbe: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.graphdb.clusterProxy.livenessProbe }}
          livenessProbe: {{- toYaml . | nindent 12 }}
          {{- end }}
      initContainers:
        - name: {{ include "graphdb-proxy.chartName" . }}-provision-settings
          image: {{ include "graphdb.image" . }}
          imagePullPolicy: {{ $.Values.deployment.imagePullPolicy }}
          env:
            - name: GRAPHDB_PUBLIC_URL
              value: {{ include "graphdb.url.public" . }}
            - name: GRAPHDB_PROXY_HTTP_PORT
              value: {{ .Values.proxy.containerPorts.http | quote }}
            - name: GRAPHDB_PROXY_RPC_PORT
              value: {{ .Values.proxy.containerPorts.rpc | quote }}
          {{- with .Values.graphdb.node.initContainerSecurityContext }}
          securityContext: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.graphdb.node.initContainerResources }}
          resources: {{ toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: graphdb-properties
              mountPath: /tmp/graphdb.properties
              subPath: graphdb.properties
            {{- if $.Values.graphdb.clusterProxy.persistence.enabled }}
            - name: graphdb-storage
              mountPath: /opt/graphdb/home
            {{- end }}
          command: [ 'sh', '-c' ]
          args:
            - |
              set -eu
              mkdir -p /opt/graphdb/home/conf/

              echo 'Configuring graphdb.properties'
              cat /tmp/graphdb.properties > /opt/graphdb/home/conf/graphdb.properties
              echo "" >> /opt/graphdb/home/conf/graphdb.properties
              echo "##### Overrides from initContainer #####" >> /opt/graphdb/home/conf/graphdb.properties

              echo 'Configuring GraphDB cluster proxy hostnames'
              echo "graphdb.hostname=$(hostname --fqdn)" >> /opt/graphdb/home/conf/graphdb.properties
              echo "graphdb.rpc.address=$(hostname --fqdn):${GRAPHDB_PROXY_RPC_PORT}" >> /opt/graphdb/home/conf/graphdb.properties
              echo "graphdb.vhosts=$(hostname --fqdn):${GRAPHDB_PROXY_HTTP_PORT}, ${GRAPHDB_PUBLIC_URL}" >> /opt/graphdb/home/conf/graphdb.properties
              echo "graphdb.external-url=${GRAPHDB_PUBLIC_URL}" >> /opt/graphdb/home/conf/graphdb.properties

              echo 'Done'

{{- end }}
