backup:
  enabled: true

  type: local

  local:
    existingPVC: local-backups

randomCM:
  enabled: true
  values:
    key1: value1
    key2: value2

# Example of a simple PVC that can be used as local backup storage.
# Ideally, you should provide something that is replicated across AZs or even regions.
extraObjects:
  - |
    {{- if $.Values.randomCM.enabled }}
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: {{ include "graphdb.fullname" $ }}-randomCM
      namespace: {{ include "graphdb.namespace" $ }}
      labels:
        {{- include "graphdb.labels" $ | nindent 4 }}
      {{- with $.Values.annotations }}
      annotations:
        {{- tpl (toYaml .) $ | nindent 4 }}
      {{- end }}
    data:
      {{- range $key, $value := $.Values.randomCM.values }}
      {{ $key }}: {{ $value | quote }}
      {{- end }}
    {{- end }}
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: local-backups
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi

extraEnv:
  - name: JVM_OPTS
    value: "-Xms512m -Xmx1024m"
  - name: GDB_REPLICA_ID
    value: "{{ $.Release.Name }}"
  - |
    - name: CLUSTER_NAME
      value: "{{ $.Release.Name }}"
  - |
    {{- if and .Values.randomCM.enabled (eq .Values.randomCM.values.key1 "value1") }}
    - name: NODE_ID
      value: test
    {{- end }}
