name: Continuous Integration

on:
  pull_request:

env:
  HELM_DOCS_IMAGE: "jnorwood/helm-docs:v1.14.2@sha256:7e562b49ab6b1dbc50c3da8f2dd6ffa8a5c6bba327b1c6335cc15ce29267979c"

jobs:
  documentation:
    name: Generate readme
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - id: checkout_repository
        name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - id: generate_helm_docs
        name: Generate Helm chart readme with helm-docs
        run: |
          docker run --rm --volume "$(pwd):/helm-docs" -u "$(id -u)" $HELM_DOCS_IMAGE

      - id: update_pull_request
        name: Update PR with readme changes
        run: |
          if ! git diff --exit-code; then
            git config --local user.name 'github-actions[bot]'
            git config --local user.email 'github-actions[bot]@users.noreply.github.com'
            git commit -am "Updated the README"
            git push
          else
            echo "Readme is up to date, nothing to push..."
          fi
