name: Continuous Integration

on:
  pull_request:
  push:
    branches: [ "master" ]

jobs:
  analyze:
    name: Analyze the Helm chart
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - id: checkout_repository
        name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - id: setup_helm
        name: Setup Helm
        uses: azure/setup-helm@dda3372f752e03dde6b3237bc9431cdc2f7a02a2 # v5.0.0
        with:
          version: v3.14.0

      - id: run_helm_lint
        name: Run Helm lint
        run: helm lint --strict .

      - id: run_helm_template
        name: Run Helm template
        run: helm template . > template_output.yaml

      - id: run_trivy_config
        name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        with:
          scan-type: config
          trivy-config: trivy.yaml
          hide-progress: false
          # Note: Until current issues are fixed, do not fail the build
          exit-code: '0'
          format: sarif
          output: trivy.sarif

      - id: run_sarif_upload
        name: Upload Trivy SARIF results
        uses: github/codeql-action/upload-sarif@bc0b696b4103f5fe60f15749af68a046868d511a #v2.25.4
        timeout-minutes: 1
        with:
          sarif_file: trivy.sarif
