# Default configuration map for provisioning the GraphDB cluster configuration.
# To change it, prepare another configuration map and update "graphdb.configs.clusterConfig"
apiVersion: {{ .Values.versions.configmap }}
kind: ConfigMap
metadata:
  name: graphdb-cluster-config-configmap
  labels:
    name: graphdb-cluster-config-configmap
data:
  cluster-config.json: |-
{{ tpl (.Files.Get "files/config/cluster-config.json" | indent 4) . }}
