{{- $configs := (.Values.graphdb.configs | default dict) }}
{{- $usersConfigMap := $configs.usersConfigMap | default ""}}
{{- if or (eq $usersConfigMap "graphdb-users-configmap") (and (not $usersConfigMap) (.Values.graphdb.security.enabled)) }}
# Default configuration map for provisioning GraphDB users.js file.
# To change it, prepare another configuration map and update "graphdb.configs.usersConfigMap"
apiVersion: {{ .Values.versions.configmap }}
kind: ConfigMap
metadata:
  name: graphdb-users-configmap
  labels:
    {{- include "graphdb.labels" . | nindent 4 }}
data:
  users.js: |-
{{ tpl (.Files.Get "files/config/users.js" | indent 4) . }}
{{- end }}
