{{- if gt (int $.Values.graphdb.clusterConfig.nodesCount) 1 }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: graphdb-proxy-properties-configmap
  labels:
    {{- include "graphdb.labels" . | nindent 4 }}
data:
  graphdb.properties: |-
{{ tpl (.Files.Get "files/config/proxy/graphdb.properties" | indent 4) . }}
{{- end }}
