# Default configuration map for provisioning GraphDB repository.
# To change it, prepare another configuration map and update "graphdb.repositoryConfigmap"
apiVersion: {{ .Values.versions.configmap }}
kind: ConfigMap
metadata:
  name: graphdb-repo-default-configmap
  labels:
    {{- include "graphdb.labels" . | nindent 4 }}
data:
  config.ttl: |-
{{ tpl (.Files.Get "files/config/graphdb-repo.default.ttl" | indent 4) . }}
