{{- if not (hasKey $.Values.graphdb.masters.persistence "volumeClaimTemplateSpec") }}
{{- range $i, $master_index := untilStep 1 (add1 $.Values.graphdb.clusterConfig.mastersCount | int ) 1 }}
---
apiVersion: {{ $.Values.versions.pvc }}
kind: PersistentVolumeClaim
metadata:
  name: graphdb-master-{{ $master_index }}-data-pvc
  labels:
    name: graphdb-master-{{ $master_index }}-data-pvc
spec:
  {{- if $.Values.graphdb.masters.persistence.volumeNamePrefix }}
    {{- if eq $.Values.graphdb.masters.persistence.volumeNamePrefix "graphdb-default-master" }}
  volumeName:  {{ $.Release.Namespace }}-{{ $.Values.graphdb.masters.persistence.volumeNamePrefix }}-{{$master_index}}-pv
    {{- else }}
  volumeName:  {{ $.Values.graphdb.masters.persistence.volumeNamePrefix }}-{{$master_index}}-pv
    {{- end }}
  {{- end }}
  storageClassName: {{ $.Values.graphdb.masters.persistence.storageClassName | default $.Values.global.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $.Values.graphdb.masters.persistence.storage }}
{{- end }}
{{- end }}
