{{- if not (hasKey $.Values.graphdb.node.persistence "volumeClaimTemplateSpec") }}
{{- range $i, $node_index := untilStep 1 (add1 (int $.Values.graphdb.clusterConfig.nodesCount) ) 1 }}
---
apiVersion: {{ $.Values.versions.pvc }}
kind: PersistentVolumeClaim
metadata:
  name: graphdb-node-{{ $node_index }}-data-pvc
  labels: {{- include "graphdb.labels" . | nindent 4 }}
    name: graphdb-node-{{ $node_index }}-data-pvc
spec:
  {{- if $.Values.graphdb.node.persistence.volumeNamePrefix }}
    {{- if eq $.Values.graphdb.node.persistence.volumeNamePrefix "graphdb-default-node" }}
  volumeName:  {{ $.Release.Namespace }}-{{ $.Values.graphdb.node.persistence.volumeNamePrefix }}-{{$node_index}}-pv
    {{- else }}
  volumeName:  {{ $.Values.graphdb.node.persistence.volumeNamePrefix }}-{{$node_index}}-pv
    {{- end }}
  {{- end }}
  storageClassName: {{ $.Values.graphdb.node.persistence.storageClassName | default $.Values.global.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $.Values.graphdb.node.persistence.storage }}
{{- end }}
{{- end }}
