{{- if or $.Values.graphdb.tools.preload.trigger $.Values.graphdb.tools.loadrdf.trigger }}
apiVersion: {{ $.Values.versions.pvc }}
kind: PersistentVolumeClaim
metadata:
  name: graphdb-node-preload-data-pvc
  labels:
    name: graphdb-node-preload-data-pvc
spec:
  volumeName:  {{ $.Release.Namespace }}-graphdb-preload-data-pv
  storageClassName: {{ $.Values.graphdb.tools.persistence.storageClassName | default $.Values.global.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $.Values.graphdb.node.persistence.storage }}
{{- end }}
