{{- if not (hasKey $.Values.graphdb.masters.persistence "volumeClaimTemplateSpec") }}
{{- $storageClassName := $.Values.graphdb.masters.persistence.storageClassName | default $.Values.global.storageClass }}
{{- if or (ne $storageClassName "standard") (ne $storageClassName "") }}
{{- if eq .Values.graphdb.masters.persistence.volumeNamePrefix "graphdb-default-master" }}
{{- range $i, $master_index := untilStep 1 (add1 $.Values.graphdb.clusterConfig.mastersCount | int ) 1 }}
#
# Default persistence volume for GraphDB workers. Data is stored on the node file system. Suitable
# for Minikube deployments.
#
# Note: Not to be used in production or multi node cluster.
#
---
apiVersion: {{ $.Values.versions.pv }}
kind: PersistentVolume
metadata:
  name: {{ $.Release.Namespace }}-graphdb-default-master-{{ $master_index }}-pv
  labels:
    name: {{ $.Release.Namespace }}-graphdb-default-master-{{ $master_index }}-pv
spec:
  claimRef:
    name: graphdb-master-{{ $master_index }}-data-pvc
    namespace: {{ $.Release.Namespace }}
  storageClassName: {{ $storageClassName }}
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: {{ $.Values.graphdb.masters.persistence.storage }}
  hostPath:
    path: {{ $.Values.deployment.storage }}/graphdb-master-{{ $master_index }}-data

{{- end }}
{{- end }}
{{- end }}
{{- end }}
