{{- if or .Values.graphdb.tools.preload.trigger .Values.graphdb.tools.loadrdf.trigger }}
#
# Default persistence volume for preloading data in GraphDB. Data is stored on the node file system. Suitable
# for Minikube deployments.
#
# Note: Not to be used in production or multi node cluster.
#
---
apiVersion: {{ $.Values.versions.pv }}
kind: PersistentVolume
metadata:
  name: {{ $.Release.Namespace }}-graphdb-preload-data-pv
  labels:
    name: {{ $.Release.Namespace }}-graphdb-preload-data-pv
spec:
  claimRef:
    name: graphdb-node-preload-data-pvc
    namespace: {{ $.Release.Namespace }}
  storageClassName: {{ $.Values.graphdb.tools.persistence.storageClassName | default $.Values.global.storageClass }}
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: {{ $.Values.graphdb.node.persistence.storage }}
  hostPath:
    path: {{ $.Values.deployment.storage }}/graphdb-worker-preload-data
{{- end }}
